// CRYPTO GRAVEYARD v4.0 - Phoenix Protocol Edition
const BAGS_REFERRAL = "https://bags.fm/?ref=cryptograveyrd";

const cryptoCorpses = [
{id:1,name:"Internet Computer (ICP)",category:"L1 Blockchain",launchDate:"2021-05",deathDate:"2021-05",amount:45000000000,description:"Launched at $750, crashed to $3. Insiders dumped on retail.",fullDescription:"Dfinity's Internet Computer launched with unprecedented hype, reaching $45 billion on day one.",causeOfDeath:"VCs who got tokens at cents dumped immediately. Price crashed 99.5%. Retail bought the top while insiders exit-liquified.",tags:["insider-dump","vc-exit"],type:"collapse",lessons:["Check unlock schedules before buying ANYTHING","Launch valuations represent peak delusion, not value","VC entry prices vs retail prices = guaranteed dump","Good tech doesn't save bad tokenomics"],
phoenix:{enabled:true,score:{rebuild:4,market:5,fairLaunch:5},
valueProposition:"Dfinity promised to replace AWS/GCP with decentralized cloud computing. The tech was genuinely innovative - canister smart contracts, reverse gas model, web-speed finality. Enterprise adoption was actually growing before the dump destroyed trust.",
theAlpha:["Decentralized compute is a real and growing need","AI boom creating massive GPU/compute demand","Canister smart contracts were genuinely innovative","VC dumps killed trust, not the underlying technology","100% fair launch eliminates the dump problem entirely"],
keyPeople:[{role:"Founder",name:"Dominic Williams"},{role:"Investor",name:"Andreessen Horowitz"},{role:"Investor",name:"Polychain Capital"}],
marketToday:"Cloud computing is $500B+ market. AWS/GCP dominate with 60%+ margins. AI compute demand exploding - GPU costs up 300% since ChatGPT. Decentralized alternatives gaining traction: Akash, Render, io.net.",
protocols:["Akash","Render","io.net","Golem"],
concept:{name:"COMPUTE FAIR",tagline:"The cloud that can't dump on you",description:"Decentralized GPU compute network. 100% fair launch - zero VC tokens. Node operators provide GPUs, earn fees. Users pay 40-60% less than AWS for AI inference. Community owns the infrastructure."},
executionPlan:["Launch node operator program - target 100 GPUs month one","Build simple API matching AWS/GCP for easy migration","Fair launch token on Bags - earned by operators and users","Focus on AI inference market first","Scale to training workloads after proving reliability"],
tokenomics:"100% fair launch. No team tokens, no VC allocation. Earned through: providing compute (70%), using compute (20%), governance (10%). Revenue from fees to stakers.",
monetization:"10% platform fee on compute transactions. At 1000 GPUs doing $100/day = $3.65M/year protocol revenue distributed to token holders.",
risks:["Cold start problem - need supply and demand simultaneously","Nvidia/cloud provider moats are strong","Decentralized compute UX historically poor"]}},

{id:2,name:"Terra/LUNA",category:"L1 Blockchain",launchDate:"2018-04",deathDate:"2022-05",amount:40000000000,description:"Algorithmic stablecoin death spiral wiped out $40B.",fullDescription:"Terra was built around UST, an algorithmic stablecoin. 20% APY on Anchor attracted massive deposits.",causeOfDeath:"UST lost peg, algorithm minted trillions of LUNA trying to defend. LUNA crashed from $119 to $0.00001 in days. The 20% yield was subsidized - reserves depleted, spiral began.",tags:["death-spiral","stablecoin"],type:"collapse",lessons:["Algorithmic stables without collateral are fragile","20% 'stable' yield is always a red flag","Reflexive mechanisms spiral both directions","150%+ collateralization needed for survival"],
phoenix:{enabled:true,score:{rebuild:4,market:5,fairLaunch:4},
valueProposition:"Terra proved massive demand exists for decentralized stablecoins - UST hit $18B market cap. Simple 'deposit and earn' UX attracted non-crypto natives. Ecosystem integration across 100+ apps made it sticky.",
theAlpha:["$18B UST at peak proved decentralized stable demand","Simple UX attracted millions of non-DeFi users","The PROBLEM was undercollateralization, not the concept","Over-collateralized designs (DAI, LUSD) survived the crash","Real 5-8% yield is achievable from actual DeFi activity"],
keyPeople:[{role:"Founder",name:"Do Kwon"},{role:"Founder",name:"Daniel Shin"},{role:"Investor",name:"Pantera Capital"},{role:"Investor",name:"Galaxy Digital"}],
marketToday:"Stablecoin market is $150B+ and growing. USDT/USDC dominate but are centralized - Tether froze $1B+ in 2023. Gap for decentralized, over-collateralized stable with sustainable yield. Ethena's USDe showing demand.",
protocols:["MakerDAO","Liquity","Ethena","Frax"],
concept:{name:"FORTRESS",tagline:"The stablecoin that survives the next crash",description:"150%+ over-collateralized stablecoin backed by diversified crypto. Sustainable 5-7% APY from real sources: Aave lending, Uniswap LP fees, liquid staking. No algorithmic minting. No fake APY. Just math that works."},
executionPlan:["Launch with ETH/stETH collateral vaults at 150% minimum","Yield aggregation from Aave, Compound, Lido","MEV-protected liquidation engine","Fair launch governance on Bags - no VC allocation","Cross-chain expansion after $50M TVL"],
tokenomics:"Governance token fair launched. No yield from inflation. Protocol fees (0.5% mint/redeem) distributed to stakers. Emergency shutdown controlled by governance.",
monetization:"0.5% fee on mint/redeem, 10% of yield generated. At $100M TVL with 6% yield = $600K/year protocol revenue.",
risks:["Smart contract risk on yield sources","Collateral price crashes in black swan","Competition from established players like MakerDAO"]}},

{id:3,name:"FTX",category:"Exchange",launchDate:"2019-05",deathDate:"2022-11",amount:32000000000,description:"SBF stole $8B customer funds. 25 years prison.",fullDescription:"FTX became third-largest exchange. SBF secretly funneled deposits to Alameda Research for risky bets and political donations.",causeOfDeath:"CoinDesk exposed Alameda's balance sheet showing it was propped up by FTT tokens. Binance announced selling FTT, triggering bank run. $8B customer hole revealed. SBF arrested, convicted on all 7 counts, sentenced to 25 years.",tags:["fraud","customer-funds"],type:"rug",
valueProposition:"FTX offered superior trading UX, innovative products (prediction markets, tokenized stocks, volatility products), and aggressive marketing (stadium naming, Super Bowl ads). SBF positioned as the 'adult in the room' - testifying to Congress, meeting with regulators. Retail and institutions trusted the brand.",
whatWentRight:["Best-in-class trading interface and mobile app","Innovative product suite (perps, options, prediction markets)","Strong brand building and mainstream recognition","Effective regulatory engagement strategy","Fast listing of new tokens attracted traders"],
whatWentWrong:["Zero separation between exchange and trading firm (Alameda)","Customer deposits used as Alameda's piggy bank","FTT token used as collateral was circular and worthless","No real board oversight or governance","Fake proof of reserves audits"],
theAlpha:["Traders want sophisticated products in simple UX - this need remains","Prediction markets have massive untapped demand (Polymarket proving it)","Regulatory engagement CAN work if you're not committing fraud","The 'trusted brand' moat is powerful but can vanish overnight","Proof of reserves must be cryptographic, not trust-based"],
keyPeople:[{role:"Founder",name:"Sam Bankman-Fried"},{role:"Co-founder",name:"Gary Wang"},{role:"Alameda CEO",name:"Caroline Ellison"},{role:"Investor",name:"Sequoia Capital"},{role:"Investor",name:"Paradigm"},{role:"Enabler",name:"SoftBank"}],
lessons:["'Trust me bro' is not proof of reserves","Regulatory capture attempts are red flags","Charismatic founders with media access are dangerous","Commingled funds = theft waiting to happen","Only cryptographic proof of reserves can be trusted","When someone seems too good to be true, they are"],phoenix:{enabled:false}},

{id:4,name:"Three Arrows Capital",category:"Hedge Fund",launchDate:"2012-01",deathDate:"2022-07",amount:18000000000,description:"Overleveraged hedge fund collapsed. Founders fled on yacht.",fullDescription:"3AC managed $18B at peak. Su Zhu and Kyle Davies built their empire on the 'supercycle' thesis - that crypto only goes up. They borrowed billions from every major lender, often without collateral, based purely on reputation.",causeOfDeath:"LUNA collapse destroyed their largest position. They went silent, ghosted creditors, and fled Singapore. Bankruptcy revealed they'd been insolvent for months. Their collapse cascaded to BlockFi, Voyager, Genesis, and Celsius.",tags:["leverage","contagion"],type:"collapse",
valueProposition:"3AC was crypto's most prestigious hedge fund. Their early calls on ETH, AVAX, and SOL built legendary status. Lenders competed to give them capital because being associated with 3AC was a status symbol. They represented 'smart money.'",
whatWentRight:["Built strong reputation through early successful trades","Created powerful network effects in crypto lending","Identified genuine opportunities early (ETH, L1s)","Masters of narrative and market psychology"],
whatWentWrong:["Borrowed without collateral based on reputation alone","No risk management - 'supercycle' thesis meant no hedging","Concentrated positions with massive leverage","Ghosted creditors instead of communicating","Fled jurisdiction when things collapsed"],
theAlpha:["Reputation-based lending is just vibes - always demand collateral","Contagion in crypto is severe because everyone lends to each other","'Smart money' can be dumb money with leverage","When funds go quiet, they're already insolvent","Counter-party risk is the hidden killer in yield products"],
keyPeople:[{role:"Founder",name:"Su Zhu"},{role:"Founder",name:"Kyle Davies"},{role:"Victim",name:"Genesis"},{role:"Victim",name:"Voyager"},{role:"Victim",name:"BlockFi"},{role:"Victim",name:"Celsius"}],
lessons:["Leverage amplifies losses exponentially","'Supercycle' thesis = zero risk management","When funds stop answering calls, they're already gone","Contagion spreads fast - 3AC took down half the industry","Never lend without collateral, no matter the reputation","If it seems too prestigious to fail, it will fail harder"],phoenix:{enabled:false}},

{id:5,name:"Anchor Protocol",category:"DeFi",launchDate:"2021-03",deathDate:"2022-05",amount:17000000000,description:"20% stable yield attracted $17B. Killed Terra.",fullDescription:"Anchor offered 20% APY on UST deposits. At peak held $17 billion - the largest DeFi protocol by TVL. The simplicity was killer: deposit stables, earn 20%, no complexity.",causeOfDeath:"The 20% yield was subsidized by Terra's reserves at a burn rate of $5M/day. When reserves depleted, the yield couldn't be maintained. UST redemptions triggered the death spiral that destroyed Terra/LUNA.",tags:["unsustainable-yield","terra"],type:"collapse",
valueProposition:"Anchor solved the 'DeFi is too complicated' problem. One-click deposit, instant 20% yield, no need to understand farming or LPs. It made DeFi accessible to normal people. The UX was genuinely excellent.",
whatWentRight:["Incredibly simple UX - grandmother could use it","Created massive demand and adoption for UST","Proved people want simple yield products","Mobile-friendly interface","Strong branding around 'stable' yields"],
whatWentWrong:["20% yield was subsidized, not earned","No transparency about yield source","Created single point of failure for entire Terra ecosystem","Encouraged deposits without educating on risks","Yield reserve depletion was visible but ignored"],
theAlpha:["Simple 'deposit and earn' UX can attract billions - the demand is real","Sustainable yield exists (5-8%) from lending, LPs, staking","Transparency about yield sources builds trust","Yield aggregators can capture this demand legitimately","Education should accompany easy UX"],
keyPeople:[{role:"Creator",name:"Terraform Labs"},{role:"Enabler",name:"Do Kwon"},{role:"Yield Source",name:"Terra Reserves"}],
lessons:["If yield seems too good to be true, ask where it comes from","Subsidized yield isn't yield - it's marketing spend","Simple UX can hide complex (and broken) mechanics","Check the yield reserve - when it depletes, game over","20% 'stable' yield is mathematically impossible to sustain"],phoenix:{enabled:false}},

{id:6,name:"Celsius Network",category:"CeFi Lending",launchDate:"2017-06",deathDate:"2022-07",amount:12000000000,description:"18% yields while gambling funds. CEO arrested.",fullDescription:"Celsius offered 18% APY. CEO Mashinsky attacked banks while secretly losing customer funds on risky DeFi plays.",causeOfDeath:"Froze $8B in withdrawals. $1.2B hole revealed. Mashinsky arrested for fraud. Users lost billions.",tags:["fraud","yield-fraud"],type:"rug",lessons:["Yields above market rate = hidden risk","CeFi opacity enables fraud","Charismatic CEOs are red flags not features","If you don't control keys, you don't control crypto"],
phoenix:{enabled:true,score:{rebuild:4,market:4,fairLaunch:5},
valueProposition:"Celsius proved users genuinely want yield on idle crypto. Simple mobile UX attracted millions of non-DeFi users. 'Unbank yourself' messaging resonated. At peak, $25B+ in assets under management.",
theAlpha:["Users genuinely want yield on idle crypto","Simple mobile UX attracted millions","Problem was opacity and fraud, not the concept","Decentralized lending works - Aave has $10B+ TVL","Trust through transparency, not charisma"],
keyPeople:[{role:"Founder",name:"Alex Mashinsky"},{role:"Investor",name:"WestCap"},{role:"Investor",name:"CDPQ"},{role:"Investor",name:"Tether"}],
marketToday:"CeFi lending is dead - BlockFi, Celsius, Voyager all bankrupt. DeFi lending thriving but complex for normies. Aave, Compound have billions but require wallet setup, gas management. Gap: Aave-level security with Celsius-level UX.",
protocols:["Aave","Compound","Morpho","Spark"],
concept:{name:"GLASS VAULT",tagline:"See everything. Trust nothing. Earn anyway.",description:"Non-custodial lending aggregator with radical transparency. Your keys, always. Real-time dashboard showing exactly where funds are deployed. No black box. Yield from battle-tested protocols only. Mobile app simplicity, DeFi security."},
executionPlan:["Build non-custodial vault contracts - users always control withdrawal","Integrate with Aave, Compound, Morpho - only battle-tested protocols","Real-time transparency dashboard - every position visible","Mobile app with one-tap deposit/withdraw","Fair launch governance on Bags"],
tokenomics:"Governance token controls fee switch and strategy allocation. 0.1% management fee on TVL distributed to stakers. No yield from inflation - pure revenue share.",
monetization:"0.1% annual fee on TVL + 5% of yield generated. At $500M TVL earning 5% = $1.75M/year protocol revenue.",
risks:["Smart contract risk on underlying protocols","Yield compression over time","Competition from protocol-native apps"]}},

{id:7,name:"BlockFi",category:"Lending",launchDate:"2017-08",deathDate:"2022-11",amount:10000000000,description:"3AC exposure, then FTX rescue with stolen funds.",fullDescription:"BlockFi pioneered crypto interest accounts for retail. Raised $1B+, had regulatory licenses, seemed like the 'safe' CeFi option. Then 3AC defaulted on loans, and FTX 'rescued' them with stolen customer funds.",causeOfDeath:"3AC default left a massive hole. FTX provided emergency credit facility - funded with stolen deposits. When FTX collapsed months later, BlockFi's rescue became its death sentence. Double-victimized by crypto's two biggest frauds.",tags:["contagion","ftx"],type:"collapse",
valueProposition:"BlockFi made crypto yield accessible to mainstream users. Clean interface, regulatory compliance, institutional backing. For many, it was the 'safe' way to earn on crypto without DeFi complexity. They pioneered the crypto credit card concept.",
whatWentRight:["Clean, trustworthy branding that appealed to normies","Regulatory engagement and state licenses","Crypto credit card was innovative","Good customer service and support","Institutional-grade security claims"],
whatWentWrong:["Massive unsecured lending to 3AC based on reputation","Accepted rescue from FTX without proper due diligence","Yield arbitrage model had hidden counterparty risk","Over-reliance on institutional lending for yield","No transparency about loan book composition"],
theAlpha:["Regulatory compliance doesn't mean safety - operations matter more","Due diligence on 'rescuers' is as important as on investments","CeFi yield = hidden counterparty risk, always","The 'safe' option can be the most dangerous","Simple yield products have massive demand if done transparently"],
keyPeople:[{role:"CEO",name:"Zac Prince"},{role:"Counterparty",name:"Three Arrows Capital"},{role:"Rescuer/Killer",name:"FTX"},{role:"Investor",name:"Valar Ventures"},{role:"Investor",name:"Tiger Global"}],
lessons:["Counterparty risk can come from 'rescuers' too","Being regulated doesn't mean being safe","Due diligence on partners matters as much as investments","Yield products inherit all counterparty risks invisibly","When someone offers to rescue you, ask where the money comes from"],phoenix:{enabled:false}},

{id:8,name:"Mt. Gox",category:"Exchange",launchDate:"2010-07",deathDate:"2014-02",amount:8500000000,description:"Lost 850,000 BTC. Original crypto catastrophe.",fullDescription:"Mt. Gox handled 70% of all Bitcoin transactions at its peak. Started as a Magic: The Gathering trading site (the name means 'Magic: The Gathering Online eXchange'). A years-long security breach went undetected.",causeOfDeath:"850,000 BTC (~$450M at the time, $50B+ at peak) was drained through a security breach that went unnoticed for years. CEO Mark Karpeles discovered the wallets were empty. Creditors entered a decade-long bankruptcy process, finally receiving partial repayment in 2024.",tags:["hack","legendary"],type:"hack",
valueProposition:"Mt. Gox was THE way to buy Bitcoin in the early days. It provided liquidity and price discovery for an asset class that barely existed. Without Mt. Gox, Bitcoin adoption would have been significantly slower. It was a necessary step in crypto's evolution.",
whatWentRight:["Provided critical early infrastructure for Bitcoin","Established price discovery mechanisms","Made Bitcoin accessible to non-technical users","Proved demand for crypto exchanges existed","Pioneered the exchange business model"],
whatWentWrong:["Hot wallet security was catastrophically weak","No regular audits of reserves","Single point of failure architecture","CEO was a programmer, not a security expert","Breach went undetected for YEARS","No insurance or backup reserves"],
theAlpha:["Exchange security is existential - one breach can kill everything","'Not your keys, not your coins' became gospel for a reason","Hot/cold wallet architecture is critical","Regular proof of reserves audits are non-negotiable","The industry matured dramatically because of Mt. Gox failure"],
keyPeople:[{role:"CEO",name:"Mark Karpeles"},{role:"Founder",name:"Jed McCaleb"},{role:"Creditors",name:"127,000 users"}],
lessons:["Not your keys, not your coins (the OG lesson)","Hot wallet security is existentially important","Audit reserves regularly - breaches can go unnoticed","Japanese bankruptcy law is very, very slow (10+ years)","The space has matured dramatically since 2014","Even dominant market leaders can fail catastrophically"],phoenix:{enabled:false}},

{id:9,name:"Voyager Digital",category:"Lending",launchDate:"2018-01",deathDate:"2022-07",amount:7000000000,description:"Lent $650M to 3AC. Falsely implied FDIC insurance.",fullDescription:"Voyager was a publicly traded crypto brokerage (VYGVF). Easy app, decent yields, stock ticker gave false legitimacy. They marketed having 'FDIC insurance' - technically true for USD up to $250K, wildly misleading for crypto.",causeOfDeath:"Voyager lent $650M to 3AC with minimal collateral - because Su Zhu was 'good for it.' When 3AC defaulted, the loan was unrecoverable. 3.5 million customers lost access to funds. The FDIC issued a cease and desist for misleading claims.",tags:["3ac-exposure","bankruptcy"],type:"collapse",
valueProposition:"Voyager offered a clean mobile app with better rates than Coinbase, plus the legitimacy of being a public company. For retail users, the stock ticker and 'FDIC insurance' messaging made it feel safe. Commission-free trading was attractive.",
whatWentRight:["Clean mobile UX that retail users loved","Commission-free trading model","Public company status provided perceived legitimacy","Good marketing and brand positioning","Wide selection of tokens"],
whatWentWrong:["Lent $650M to 3AC without adequate collateral","Misleading FDIC insurance marketing","No risk management on loan book concentration","Public company oversight didn't catch issues","Put reputation above actual safety"],
theAlpha:["FDIC insurance does NOT cover crypto - never will","Public company status ≠ legitimate operations","Lending without collateral is just giving money away","Concentration risk in loan books is deadly","Always read the fine print on 'insurance' claims"],
keyPeople:[{role:"CEO",name:"Stephen Ehrlich"},{role:"Debtor",name:"Three Arrows Capital"},{role:"Regulator",name:"FDIC (cease and desist)"}],
lessons:["FDIC insurance messaging was fraudulent misdirection","Public company status provides zero protection","Reputation-based lending without collateral is insane","Concentration risk (one borrower) can kill a company","Read terms carefully - 'USD insured' ≠ 'crypto insured'","3.5M users learned the hardest lesson"],phoenix:{enabled:false}},

{id:10,name:"Bitfinex Hack",category:"Exchange",launchDate:"2012-01",deathDate:"2016-08",amount:4500000000,description:"119,756 BTC stolen. Hackers were married couple doing rap videos.",fullDescription:"Bitfinex lost 119,756 BTC in 2016 through a sophisticated hack targeting their multi-sig implementation. Years later, DOJ traced the funds to Ilya Lichtenstein and Heather Morgan - a married couple where Heather made cringe rap videos as 'Razzlekhan.'",causeOfDeath:"Hackers exploited BitGo's multi-sig implementation to authorize fraudulent transactions. The stolen BTC sat dormant for years. DOJ arrested the couple in 2022 and seized $3.6B. Bitfinex socialized losses across users with BFX tokens.",tags:["hack","recovered"],type:"hack",
valueProposition:"Bitfinex was a leading exchange for sophisticated traders, offering margin trading and lending markets. Their recovery approach - issuing BFX tokens to affected users that could be redeemed later - was innovative (if controversial).",
whatWentRight:["Exchange survived despite massive hack","BFX token recovery mechanism was creative","Eventually recovered most stolen funds (via DOJ)","Multi-sig was an improvement over single keys","Continued operating and rebuilt trust"],
whatWentWrong:["Multi-sig implementation had critical vulnerability","$72M (at the time) lost to single exploit","Security audit didn't catch the flaw","Hackers weren't caught for 6 years","Socialized losses to all users via haircut"],
theAlpha:["Even sophisticated security (multi-sig) can be compromised","Stolen crypto can be traced - blockchain is forever","Time doesn't make stolen crypto safe to spend","The strangest people end up in crypto crime (Razzlekhan)","Recovery IS possible - don't give up on hacked funds"],
keyPeople:[{role:"Hacker",name:"Ilya Lichtenstein"},{role:"Hacker",name:"Heather 'Razzlekhan' Morgan"},{role:"Security",name:"BitGo"},{role:"Exchange",name:"Bitfinex"}],
lessons:["Multi-sig is better but not bulletproof","Stolen crypto can be traced and recovered (eventually)","Hot wallet architecture carries inherent risk","Security audits can miss critical vulnerabilities","Blockchain transparency means criminals can be caught years later","If you steal crypto, don't make rap videos about being a boss"],phoenix:{enabled:false}},

{id:11,name:"Axie Infinity",category:"GameFi",launchDate:"2018-03",deathDate:"2022-06",amount:4200000000,description:"Play-to-earn became work-to-lose.",fullDescription:"2.7M daily users. Filipinos quit jobs to play. Required endless new players to sustain payouts.",causeOfDeath:"Ponzi dynamics unsustainable. SLP crashed 95%. Ronin bridge hack ($625M) was killing blow. Players realized they were working, not playing.",tags:["gamefi","ponzinomics"],type:"collapse",lessons:["Game must be fun WITHOUT earning","Play-to-earn requires infinite growth","Token emissions must tie to real revenue","Two-token models can spiral quickly"],
phoenix:{enabled:true,score:{rebuild:5,market:5,fairLaunch:4},
valueProposition:"Axie proved crypto gaming could achieve mainstream adoption. 2.7 million daily users earning real income. Filipino players quit jobs to play full-time. The core insight was valid: people spend enormous time in games, so let them earn while playing.",
theAlpha:["2.7M daily users proved crypto gaming demand is REAL","Breeding mechanics created emotional attachment to NFTs","Community guilds showed power of coordinated play","Mobile gaming is $90B+ market barely touched by crypto","Battle mechanics were engaging - the game had real depth"],
keyPeople:[{role:"Founder",name:"Trung Nguyen"},{role:"Founder",name:"Aleksander Larsen"},{role:"Investor",name:"Andreessen Horowitz"},{role:"Investor",name:"Paradigm"}],
marketToday:"Gaming is a $200B+ industry. Mobile gaming alone is $90B. Play-to-earn is dead, but 'play-AND-earn' emerging. Successful examples: Pixels, Big Time. Gap: fair-launched mobile game where earning enhances fun.",
protocols:["Solana Gaming","Immutable X","Arbitrum Nova"],
concept:{name:"QUEST PROTOCOL",tagline:"The game you'd play even if tokens were worthless",description:"Mobile-first RPG where the core loop is genuinely fun. Tokens earned through gameplay but capped daily to prevent grinding culture. NFTs are cosmetic flexes, not pay-to-win. Revenue from battle passes and cosmetics - proven $50B+ market."},
executionPlan:["Build genuinely fun mobile game first - 3 month prototype with no crypto","Soft launch to test retention - target 20% Day-30 before adding tokens","Add optional token earning - capped at $5-10/day","Fair launch governance on Bags - earned through achievements","Revenue share to stakers from cosmetic sales"],
tokenomics:"Fixed 100M supply. No emissions - tokens from one-time achievement unlocks. Revenue from cosmetics: 70% to stakers, 20% treasury, 10% dev. 5% burn on cosmetic purchases.",
monetization:"Battle passes ($10/season), cosmetic NFTs ($1-100), tournament entry (5% rake). Target: $2 ARPU on 500K MAU = $1M/month to token holders.",
risks:["Mobile dev is expensive and competitive","Crypto gaming reputation damaged","App store NFT policies are restrictive"]}},

{id:12,name:"OneCoin",category:"Ponzi",launchDate:"2014-01",deathDate:"2017-10",amount:4000000000,description:"No blockchain existed. Crypto Queen vanished with $4B.",fullDescription:"Ruja Ignatova, the 'Crypto Queen,' promised OneCoin would surpass Bitcoin. She filled stadiums with believers across 175 countries. The problem: there was no blockchain. No coins. Just a number in a database controlled by the company.",causeOfDeath:"Ruja flew from Sofia to Athens in October 2017 and vanished - never seen again. FBI placed her on Most Wanted list with $250K reward. Her brother Konstantin pled guilty. $4B+ extracted from victims worldwide who believed they were buying crypto.",tags:["ponzi","fbi-wanted"],type:"rug",
valueProposition:"OneCoin exploited the fear of missing out on 'the next Bitcoin.' For people who missed BTC's rise, this was their second chance. The MLM structure made participants feel like entrepreneurs, not victims. Ruja's charisma and the spectacle of stadium events created cult-like belief.",
whatWentRight:["Masterclass in marketing and persuasion (study it)","Created genuine belief and community (for evil)","Exploited real FOMO around Bitcoin","Stadium events created powerful social proof","MLM structure turned victims into promoters"],
whatWentWrong:["No blockchain existed - it was just a SQL database","Centralized 'mining' that created fake coins","No way to withdraw or sell coins","Classic MLM recruitment structure","Completely fabricated technology claims"],
theAlpha:["VERIFY THE BLOCKCHAIN EXISTS - check block explorers","Cult of personality is the biggest red flag","If you can't see it on a public explorer, it's not real","MLM + crypto = exponential scam potential","Never trust - always verify on-chain","Understanding this scam helps spot future ones"],
keyPeople:[{role:"Founder",name:"Ruja Ignatova (FBI Most Wanted)"},{role:"Co-founder",name:"Konstantin Ignatov (arrested)"},{role:"Victims",name:"3+ million people in 175 countries"}],
lessons:["Verify blockchain exists on public explorer","Stadium events and charisma are red flags, not validation","MLM structure means victims recruit victims","If you can't withdraw, you don't own anything","Scammers vanish - $4B can buy a lot of hiding","Study this to recognize similar patterns"],phoenix:{enabled:false}},

{id:13,name:"Olympus DAO",category:"DeFi",launchDate:"2021-03",deathDate:"2022-01",amount:4000000000,description:"(3,3) promised 7,000% APY. Crashed 99%.",fullDescription:"Olympus pioneered 'DeFi 2.0' with protocol-owned liquidity and (3,3) game theory. The meme convinced everyone: if we all stake together, we all win together. APY reached 7,000%+. At peak, $4B+ market cap.",causeOfDeath:"(3,3) assumed everyone cooperates indefinitely. But game theory in markets predicts defection - and that's exactly what happened. Once a few large holders sold, the game theory flipped to (sell, sell). OHM crashed from $1,400 to under $15.",tags:["ponzinomics","defi-2.0"],type:"collapse",
valueProposition:"Olympus introduced genuinely innovative concepts: protocol-owned liquidity (POL) meant the protocol owned its trading pairs instead of renting them. Bonding let users buy OHM at a discount by providing LP tokens. These ideas WORK - they just can't sustain 7,000% APY.",
whatWentRight:["Protocol-owned liquidity concept was genuinely innovative","Bonding mechanism for acquiring liquidity was novel","Created massive community coordination","POL concept lives on in Velodrome/Aerodrome","Treasury management approach was interesting"],
whatWentWrong:["7,000% APY is mathematically unsustainable","(3,3) game theory assumes infinite cooperation","Rebasing mechanics were confusing and easily manipulated","When confidence cracked, spiral was violent","Memes became monetary policy"],
theAlpha:["POL concept is valid and thriving (Velodrome does $100M+ daily volume)","Bonding mechanisms work at sustainable rates","Community coordination IS powerful when not based on impossible APY","Treasury DAOs have a future with realistic expectations","The failure was the APY promise, not the underlying innovations"],
keyPeople:[{role:"Founder",name:"Zeus (pseudonymous)"},{role:"Concept",name:"(3,3) Game Theory"}],
lessons:["7,000% APY is mathematically impossible to sustain","Game theory with real money leads to defection","Rebasing tokens are confusing and easily manipulated","Valid innovations (POL) can be ruined by ponzinomics","Memes are not monetary policy","Study what worked (POL) separately from what failed (APY)"],phoenix:{enabled:false}},

{id:14,name:"Africrypt",category:"Ponzi",launchDate:"2019-01",deathDate:"2021-04",amount:3600000000,description:"Brothers vanished with 69,000 BTC. Told victims not to call police.",fullDescription:"The Cajee brothers (Ameer, 17 and Raees, 21) ran Africrypt from South Africa, promising AI-powered trading returns. They accumulated 69,000 BTC from investors before executing one of history's largest exit scams.",causeOfDeath:"In April 2021, they claimed Africrypt was hacked and explicitly told investors NOT to report to police as it would 'slow down recovery efforts.' Then they vanished. The 'hack' was fake - they simply took everything.",tags:["exit-scam","brothers"],type:"rug",
valueProposition:"Africrypt promised sophisticated AI trading algorithms delivering consistent returns. In regions with limited banking access, crypto investment platforms were seen as legitimate alternatives. The brothers' youth was seen as tech-savvy credibility, not a red flag.",
whatWentRight:["Tapped into real demand for investment alternatives in Africa","Built trust through consistent (fake) returns","Exploited the 'young tech genius' narrative","Operated in jurisdiction with limited crypto regulation"],
whatWentWrong:["Classic Ponzi structure - new money paid old investors","'AI trading' claims were completely fabricated","No proof of trading activity or reserves","Telling victims not to contact police was audacious red flag","Brothers were teenagers running a $3.6B operation"],
theAlpha:["If ANYONE tells you not to contact authorities, that's the biggest red flag possible","'AI trading' claims are almost always fake - demand proof","Youth ≠ tech credibility, especially with your money","Jurisdictional arbitrage is used by scammers deliberately","Consistent returns without verifiable trading = Ponzi"],
keyPeople:[{role:"Founder",name:"Ameer Cajee (17)"},{role:"Founder",name:"Raees Cajee (21)"},{role:"Victims",name:"South African investors"}],
lessons:["If they say 'don't contact police,' IMMEDIATELY contact police","Teenagers shouldn't manage billions without oversight","'AI trading' is almost always a lie - demand proof of trades","Consistent high returns without verification = classic Ponzi","Check the jurisdiction - scammers choose weak regulatory environments"],phoenix:{enabled:false}},

{id:15,name:"BitConnect",category:"Ponzi",launchDate:"2016-01",deathDate:"2018-01",amount:3500000000,description:"OG crypto Ponzi. 1% daily returns. Carlos Matos meme immortalized.",fullDescription:"BitConnect promised 1% daily returns through a 'volatility trading bot.' Users locked BTC, received daily BCC payouts. Carlos Matos screaming 'BITCONNEEECT!' at a conference became an immortal meme.",causeOfDeath:"Texas and North Carolina issued cease and desist orders. Platform shut down overnight. BCC crashed from $400+ to under $1. Carlos Matos became a meme, victims became broke. Founder Satish Kumbhani indicted but never caught.",tags:["ponzi","mlm","meme"],type:"rug",
valueProposition:"BitConnect offered seemingly guaranteed returns in a volatile market. The 'lending' model (lock your BTC, receive daily payments) felt safer than trading. Conference events with testimonials created social proof. For many, it was their first crypto investment.",
whatWentRight:["Created massive community engagement","Conference events built genuine excitement","The meme lives on - incredible marketing even if evil","Showed power of testimonials and social proof","First major crypto Ponzi - taught industry lessons"],
whatWentWrong:["1% daily = 3,678% annually (impossible)","'Trading bot' never existed","Classic Ponzi - new deposits paid old investors","Locked funds meant victims couldn't exit","Regulatory action triggered instant collapse"],
theAlpha:["1% daily is mathematically impossible (3,678% APY)","Any 'guaranteed return' in crypto is a scam","Lending platforms with fixed returns are Ponzis","Meme energy and hype ≠ legitimacy","Regulatory action can collapse schemes instantly","Study Carlos Matos to understand how hype captures people"],
keyPeople:[{role:"Founder",name:"Satish Kumbhani (indicted, at large)"},{role:"Promoter",name:"Carlos Matos (meme legend)"},{role:"Regulator",name:"Texas Securities Board"}],
lessons:["1% daily = 3,678% annually - do the math","'Trading bot' promises are always lies","Locked funds = you can't exit when it collapses","Meme conferences and screaming promoters are red flags","Regulatory cease and desist = immediate collapse","The bigger the hype, the harder the fall"],phoenix:{enabled:false}},

{id:16,name:"Genesis Trading",category:"Lending",launchDate:"2013-01",deathDate:"2023-01",amount:3000000000,description:"DCG's lending arm. $2.36B exposure to 3AC.",fullDescription:"Genesis was Digital Currency Group's institutional lending arm - the 'Goldman Sachs of crypto.' They facilitated billions in loans between institutions, acting as the backbone of crypto's shadow banking system.",causeOfDeath:"Genesis lent $2.36B to 3AC based on reputation. When 3AC defaulted, the hole was too big to fill. Contagion spread to Gemini's Earn program (340K users affected). DCG's attempted bailout failed. Bankruptcy revealed the interconnected house of cards.",tags:["contagion","gemini"],type:"collapse",
valueProposition:"Genesis provided institutional-grade lending infrastructure. For hedge funds and trading firms, they were the primary source of leverage. Gemini Earn users got yield through Genesis without knowing it. They were crypto's wholesale lending market.",
whatWentRight:["Built critical institutional infrastructure","Facilitated price discovery through lending markets","Provided liquidity that helped crypto mature","Institutional reputation attracted capital"],
whatWentWrong:["Massive unsecured lending to 3AC","No transparency to retail users (Gemini Earn)","Concentration risk - too much to one borrower","DCG conflict of interest in attempted rescue","Shadow banking with no oversight"],
theAlpha:["Institutional lending is a hidden layer of risk in yield products","Your yield app probably uses wholesale lenders you've never heard of","Concentration risk in loan books is deadly","Contagion spreads through lending relationships","Ask 'who is my yield app lending to?' - if they won't say, don't deposit"],
keyPeople:[{role:"Parent",name:"Digital Currency Group"},{role:"Partner",name:"Gemini Earn"},{role:"Debtor",name:"Three Arrows Capital"},{role:"CEO",name:"Michael Moro"}],
lessons:["Yield programs inherit all counterparty risks invisibly","Institutional lenders are the hidden risk layer","Concentration in loan books kills lenders","Contagion spreads through interconnected lending","Ask where your yield comes from - trace the chain"],phoenix:{enabled:false}},

{id:17,name:"StepN",category:"GameFi",launchDate:"2021-12",deathDate:"2022-06",amount:3000000000,description:"Move-to-earn required $1,000 sneaker NFTs to walk.",fullDescription:"StepN gamified fitness - buy virtual sneakers (starting at $1,000+), walk or run, earn GMT/GST tokens. At peak, 3M+ daily users, $3B market cap. People were literally running to earn crypto.",causeOfDeath:"China banned the app for mainland users (huge market). Ponzi dynamics required endless new buyers for expensive sneakers. When growth slowed, token prices crashed. Users holding $1,000+ sneakers watched value evaporate overnight.",tags:["move-to-earn","ponzinomics"],type:"collapse",
valueProposition:"StepN brilliantly combined two massive trends: fitness apps and crypto rewards. The core insight was valid - people already walk, why not reward them? The execution created genuine behavior change; users actually exercised more.",
whatWentRight:["Created real behavior change - users exercised more","Brilliant UX that made crypto accessible","Built genuine community around fitness","Proved 'X-to-earn' could achieve mass adoption","3M+ daily active users at peak"],
whatWentWrong:["$1,000+ entry barrier was exclusionary and unsustainable","Token emissions far exceeded any possible revenue","Required endless new buyers to sustain prices","Geographic regulatory risk (China ban)","Two-token model (GMT/GST) created complexity and death spiral"],
theAlpha:["Fitness + rewards has real demand - just needs sustainable model","Free entry with optional premium is the right model","Single token models are simpler and safer","Geographic concentration is existential risk","Revenue must exceed emissions or math doesn't work"],
keyPeople:[{role:"Founder",name:"Yawn Rong"},{role:"Founder",name:"Jerry Huang"},{role:"Investor",name:"Sequoia Capital"},{role:"Investor",name:"Binance Labs"}],
lessons:["$1,000 entry barrier guarantees eventual collapse","Move-to-earn works but must be free to start","China regulatory risk can kill overnight","Two-token models create death spiral risk","If new users fund old users, it's a Ponzi"],phoenix:{enabled:false}},

{id:18,name:"PlusToken",category:"Ponzi",launchDate:"2018-05",deathDate:"2019-06",amount:2900000000,description:"Chinese MLM Ponzi. 3 million victims. 10-30% monthly.",fullDescription:"PlusToken was marketed as an 'AI arbitrage bot' delivering 10-30% monthly returns. Operated primarily in China and Korea through aggressive MLM recruitment. 3 million+ victims lost a combined $2.9B before authorities shut it down.",causeOfDeath:"Chinese authorities arrested 109 members of the operation. Investigation revealed classic Ponzi - no trading bot existed, no arbitrage was performed. New deposits paid old investors until music stopped.",tags:["ponzi","china"],type:"rug",
valueProposition:"PlusToken exploited crypto's complexity to claim 'arbitrage opportunities' that retail couldn't access. The MLM structure made victims feel like entrepreneurs. In regions with limited investment options, 10%+ monthly seemed possible in crypto's volatile markets.",
whatWentRight:["Masterful exploitation of crypto's perceived complexity","MLM structure created viral growth","Localized marketing for Asian markets","Created FOMO around 'exclusive' AI technology"],
whatWentWrong:["No trading bot or arbitrage operation existed","Classic Ponzi - new money paid old investors","10-30% monthly is 214-2,230% annually (impossible)","MLM structure meant victims recruited victims","Authorities eventually caught on"],
theAlpha:["'AI arbitrage bot' is almost always a lie - demand proof","10%+ monthly returns are mathematically impossible sustainably","MLM + crypto = exponential scam potential","Localized scams can still be massive ($2.9B)","If you can't verify the trading activity, assume it's fake"],
keyPeople:[{role:"Operators",name:"109 arrested members"},{role:"Victims",name:"3+ million across China/Korea"}],
lessons:["Arbitrage bot claims require proof of actual trades","10-30% monthly = obvious Ponzi (do the annual math)","MLM recruitment structure is a massive red flag","Complexity is used to hide simple fraud","3 million victims shows scale of crypto scam potential"],phoenix:{enabled:false}},

{id:19,name:"BAYC",category:"NFT",launchDate:"2021-04",deathDate:"2024-01",amount:2800000000,description:"Floor crashed 93% from 150 ETH. Celebrity holders rekt.",fullDescription:"Bored Ape Yacht Club became THE status symbol of crypto. Owning one meant you'd 'made it.' Celebrities paid millions - Justin Bieber bought one for $1.3M. Floor reached 150 ETH ($400K+). Yuga Labs raised at $4B valuation.",causeOfDeath:"NFT winter hit hard. Speculative premium evaporated. Floor crashed from 150 ETH to under 10 ETH (93%+ drop). Bieber's $1.3M ape worth ~$60K. The 'community' and 'utility' couldn't sustain speculation-driven prices.",tags:["nft-winter","celebrities"],type:"collapse",
valueProposition:"BAYC sold belonging and status. Holders joined an exclusive club with celebrity members, yacht parties, and commercial rights to their apes. Yuga Labs kept building (Otherside metaverse, ApeCoin) to justify valuations. For many, it felt like buying into an elite network.",
whatWentRight:["Created genuine community and cultural moment","Commercial rights to art was innovative","Consistent building (Otherside, ApeCoin, Kodas)","Celebrity adoption created massive FOMO","Proved NFTs could be cultural phenomena"],
whatWentWrong:["Prices driven by speculation, not utility","Celebrity purchases marked the exact top","'Utility' never matched 6-figure valuations","Metaverse promises remain unfulfilled","Liquidity dried up in bear market"],
theAlpha:["Celebrity NFT purchases mark market tops","Community and utility can't sustain speculation premiums","NFT value = art value + speculation premium (premium evaporates)","Commercial rights are interesting but not worth $400K","Bear markets reveal what's real vs speculation"],
keyPeople:[{role:"Creator",name:"Yuga Labs"},{role:"Founders",name:"Gordon Goner, Gargamel"},{role:"Celebrity Holder",name:"Justin Bieber ($1.3M → $60K)"},{role:"Celebrity Holder",name:"Steph Curry"},{role:"Celebrity Holder",name:"Eminem"}],
lessons:["When celebrities buy, the top is in","Speculation premium always evaporates eventually","Community can't sustain 6-figure floor prices","NFT utility rarely justifies NFT prices","Status symbols only work when everyone's rich"],phoenix:{enabled:false}},

{id:20,name:"Thodex",category:"Exchange",launchDate:"2017-01",deathDate:"2021-04",amount:2000000000,description:"Turkish CEO fled with $2B. Sentenced to 11,196 years.",fullDescription:"Thodex was Turkey's largest crypto exchange. CEO Faruk Fatih Özer built trust through aggressive marketing, including giving away Dogecoins. One day he announced 'partnership negotiations' requiring temporary withdrawal halt - then fled to Albania with $2B.",causeOfDeath:"400,000 users woke up to frozen accounts and a CEO on the run. Turkish authorities issued Interpol red notice. Özer was caught in Albania after 2 years, extradited, and sentenced to 11,196 years in prison - Turkey's longest ever sentence.",tags:["exit-scam","turkey"],type:"rug",
valueProposition:"Thodex offered easy fiat on-ramps in Turkey, where crypto adoption was high due to lira instability. Aggressive promotions (free Doge giveaways) built user base. For Turks seeking inflation hedges, Thodex was accessible and local.",
whatWentRight:["Identified real market need (lira instability)","Built largest local exchange in Turkey","Effective marketing and user acquisition","Easy fiat on/off ramps for local currency"],
whatWentWrong:["Single person controlled all funds","No proof of reserves or audits","'Partnership negotiations' was obvious lie","Sudden withdrawal freeze = classic exit scam pattern","Trust was based on marketing, not verification"],
theAlpha:["Sudden 'maintenance' or 'partnership negotiations' = run","Local exchanges in unstable economies are high risk","Single founder control of funds is existential risk","11,196 year sentence shows severity of crypto crime","If withdrawals freeze unexpectedly, assume the worst"],
keyPeople:[{role:"Founder/Thief",name:"Faruk Fatih Özer"},{role:"Victims",name:"400,000 Turkish users"}],
lessons:["'Temporary withdrawal halt for negotiations' = exit scam","Local exchanges without audits are extremely risky","Single founder control means single point of theft","Watch for sudden maintenance announcements","11,196 years proves authorities take this seriously now"],phoenix:{enabled:false}},

{id:21,name:"Solidly",category:"DeFi",launchDate:"2022-02",deathDate:"2022-03",amount:2000000000,description:"Andre Cronje quit crypto. $2B TVL fled overnight.",fullDescription:"Andre Cronje (Yearn founder, DeFi legend) launched Solidly with ve(3,3) tokenomics - combining Curve's vote-escrow model with Olympus concepts. $2B TVL flooded in within weeks based purely on Andre's reputation.",causeOfDeath:"One month after launch, Andre tweeted he was 'leaving crypto.' Panic ensued. TVL fled overnight. The protocol worked fine technically - but confidence evaporated when the figurehead left. Proved single-founder dependency is fatal.",tags:["abandoned","andre-cronje"],type:"collapse",
valueProposition:"Solidly introduced ve(3,3) - a genuinely innovative model combining vote-escrow tokenomics with protocol-owned liquidity. Andre's track record (Yearn, Keep3r) gave instant credibility. The model actually works - Velodrome proved it.",
whatWentRight:["ve(3,3) model was genuinely innovative","Attracted massive TVL on reputation alone","Model lives on successfully in Velodrome/Aerodrome","Proved appetite for advanced tokenomics"],
whatWentWrong:["100% dependent on one person's involvement","No decentralized team or governance","Andre's departure triggered confidence collapse","Protocol was fine - people weren't","Built on personality, not institution"],
theAlpha:["ve(3,3) model works - Velodrome does $100M+ daily volume","Single-founder dependency is existential risk","Decentralized teams survive founder departures","Build institutions, not personality cults","The tech was fine - the social layer failed"],
keyPeople:[{role:"Founder",name:"Andre Cronje"},{role:"Successor",name:"Velodrome (forked and succeeded)"}],
lessons:["Protocols dependent on one person will die with their involvement","Decentralized teams are more resilient","Andre's departure proved the concept worked (Velodrome thrived)","Reputation-driven TVL flees at first sign of trouble","Build teams, not personality cults"],phoenix:{enabled:false}},

{id:22,name:"IRON/TITAN",category:"DeFi",launchDate:"2021-05",deathDate:"2021-06",amount:1900000000,description:"Even Mark Cuban got rugged. TITAN went to literal zero.",fullDescription:"Iron Finance built a partially-collateralized algorithmic stablecoin on Polygon. IRON was 75% USDC + 25% TITAN. Mark Cuban publicly invested and promoted it. Then came the first major algo stable death spiral.",causeOfDeath:"Large holders sold TITAN, breaking the peg mechanism. Algorithm minted more TITAN to restore peg, crashing TITAN price further. Classic death spiral. TITAN went from $60 to $0.000000035 - essentially zero. Cuban lost money and called for regulation.",tags:["death-spiral","celebrity-victim"],type:"collapse",
valueProposition:"Iron Finance offered yield farming on a 'stable' asset. Partial collateralization seemed clever - more capital efficient than 100% backing. Mark Cuban's endorsement added credibility. Polygon's low fees made it accessible.",
whatWentRight:["Identified desire for capital-efficient stables","Built on Polygon for accessibility","Attracted major investor (Cuban) attention","Demonstrated partial collateral concept"],
whatWentWrong:["Partial collateralization creates death spiral risk","Algorithm couldn't handle large redemptions","TITAN backing was circular and fragile","Celebrity endorsement didn't mean due diligence","Went to essentially zero in hours"],
theAlpha:["Partial collateralization = partial safety = eventual death spiral","Even billionaires don't do proper due diligence","Celebrity endorsements are marketing, not validation","Algo stables need 100%+ collateral to survive","Death spirals happen faster than you can react"],
keyPeople:[{role:"Protocol",name:"Iron Finance"},{role:"Celebrity Victim",name:"Mark Cuban"},{role:"Victim",name:"Polygon DeFi users"}],
lessons:["Even billionaires get rugged - do your own research","Partially-collateralized stables will eventually spiral","Death spirals happen in hours, not days","Celebrity endorsement ≠ safety","If it went to $0.000000035, the math was broken from the start"],phoenix:{enabled:false}},

{id:23,name:"Finiko",category:"Ponzi",launchDate:"2019-01",deathDate:"2021-07",amount:1500000000,description:"Russian Ponzi promising 30% monthly. Founder arrested.",fullDescription:"Finiko operated across Russia and CIS countries promising 30% monthly returns through 'automated trading systems.' Founder Kirill Doronin built a cult-like following with flashy lifestyle content and promises of financial freedom.",causeOfDeath:"Russian authorities arrested Doronin and associates. Investigation revealed zero trading activity - pure Ponzi. An estimated $1.5B collected from victims, mostly in Russia, Kazakhstan, and other former Soviet states.",tags:["ponzi","russia"],type:"rug",
valueProposition:"Finiko exploited economic uncertainty in Russia and CIS countries. 30% monthly promised escape from limited local investment options. Doronin's influencer-style marketing (luxury cars, lifestyle) made wealth seem achievable. Telegram communities created belonging.",
whatWentRight:["Effective social media marketing","Built strong community via Telegram","Localized approach for Russian-speaking markets","Founder's lifestyle content created aspiration"],
whatWentWrong:["30% monthly = 2,230% annually (impossible)","Zero actual trading - pure Ponzi","Targeted economically vulnerable populations","Telegram communities became echo chambers","No way to verify any trading claims"],
theAlpha:["30% monthly is mathematically impossible (do the math: 2,230% APY)","Lifestyle influencer marketing is a red flag","Telegram communities can be manipulation tools","Regional scams exploit local economic conditions","If founder flaunts wealth, ask where it comes from"],
keyPeople:[{role:"Founder",name:"Kirill Doronin (arrested)"},{role:"Victims",name:"Russian/CIS investors"}],
lessons:["30% monthly = 2,230% annually - obviously impossible","Lifestyle flexing by founders is a warning sign","Telegram communities create false social proof","Economic hardship makes people vulnerable to scams","'Automated trading' claims are almost always lies"],phoenix:{enabled:false}},

{id:24,name:"Wonderland TIME",category:"DeFi",launchDate:"2021-09",deathDate:"2022-01",amount:1200000000,description:"$1B treasury managed by convicted felon 0xSifu.",fullDescription:"Wonderland was the largest Olympus DAO fork, built on Avalanche by Daniele Sestagalli. At peak, the treasury held $1B+. Then ZachXBT revealed that treasury manager '0xSifu' was actually Michael Patryn - co-founder of the QuadrigaCX disaster.",causeOfDeath:"ZachXBT's investigation revealed 0xSifu was Michael Patryn, convicted fraudster and QuadrigaCX co-founder (whose other founder died with $190M in user funds). Community trust evaporated instantly. Treasury was drained through panic redemptions.",tags:["criminal","ohm-fork"],type:"collapse",
valueProposition:"Wonderland offered Olympus-style returns with Daniele's credibility (Abracadabra, Spell). The treasury was meant to generate yield for token holders. Community governance and transparency were promised. It felt like participating in a community-owned hedge fund.",
whatWentRight:["Built massive treasury ($1B+) quickly","Strong community engagement","Daniele had legitimate DeFi credibility","Treasury management concept was interesting"],
whatWentWrong:["Treasury manager was anonymous criminal","No background checks on key personnel","Daniele vouched for someone he didn't verify","Community governance couldn't prevent insider risk","Anonymous team = unknown risks"],
theAlpha:["Anonymous treasury managers are unacceptable risk","Background checks on key personnel are essential","'Trust me' from founders isn't due diligence","Even legitimate builders can vouch for criminals","If someone controls funds, their identity matters"],
keyPeople:[{role:"Founder",name:"Daniele Sestagalli"},{role:"Treasury Manager",name:"0xSifu (Michael Patryn)"},{role:"Investigator",name:"ZachXBT"},{role:"Connected Scandal",name:"QuadrigaCX"}],
lessons:["Anonymous treasury managers = unacceptable risk","Always verify identity of anyone controlling funds","Founder vouching isn't the same as due diligence","ZachXBT investigations should be taken seriously","Criminal history doesn't disappear with a pseudonym"],phoenix:{enabled:false}},

{id:25,name:"Ronin Bridge",category:"Bridge",launchDate:"2021-06",deathDate:"2022-03",amount:625000000,description:"North Korea's Lazarus Group stole $625M. Unnoticed for 6 days.",fullDescription:"Ronin was Axie Infinity's sidechain bridge, holding massive ETH/USDC to back in-game assets. North Korea's Lazarus Group compromised validator keys through a fake job offer phishing attack on a Sky Mavis engineer.",causeOfDeath:"Hackers gained control of 5 of 9 validator keys (only 4 were ever active). Drained $625M in ETH and USDC. The theft went UNNOTICED for 6 days until a user tried to withdraw and couldn't. Nation-state level attack on insufficient infrastructure.",tags:["hack","north-korea"],type:"hack",
valueProposition:"Ronin enabled Axie's massive scale by moving transactions off Ethereum mainnet. The bridge held user deposits backing in-game assets. It was critical infrastructure for crypto's biggest game, enabling millions of players.",
whatWentRight:["Enabled Axie's scale (2.7M daily users)","Made crypto gaming affordable (low fees)","Solved real Ethereum scaling problem","Critical infrastructure for GameFi"],
whatWentWrong:["Only 5 validators total (4 active) - way too centralized","Social engineering compromised engineer","Theft undetected for 6 DAYS","No monitoring or alerts on large withdrawals","Nation-state attackers weren't considered in threat model"],
theAlpha:["Bridges are high-value targets for nation-state hackers","Validator centralization is existential risk","Monitoring and alerts are essential for large treasuries","Social engineering (fake job offers) is a real attack vector","If it holds $625M, security should match"],
keyPeople:[{role:"Attacker",name:"Lazarus Group (North Korea)"},{role:"Victim",name:"Sky Mavis / Axie Infinity"},{role:"Vector",name:"Phished engineer"}],
lessons:["Bridges holding billions need nation-state level security","5 validators for $625M is criminally negligent","6 days unnoticed = no monitoring existed","Fake job offer phishing is a real attack vector","If North Korea wants your funds, plan accordingly"],phoenix:{enabled:false}},

{id:26,name:"Mango Markets",category:"DeFi",launchDate:"2021-08",deathDate:"2022-10",amount:114000000,description:"Avraham Eisenberg manipulated oracle, bragged, got arrested.",fullDescription:"Mango was Solana's leading perps DEX. Avraham Eisenberg executed a sophisticated oracle manipulation attack - pumping MNGO price 10x through coordinated trading, then borrowing $114M against inflated collateral. He bragged it was 'legal market manipulation.'",causeOfDeath:"Eisenberg publicly claimed the attack was 'a highly profitable trading strategy' and negotiated to return some funds. DOJ disagreed - arrested him for commodities fraud and manipulation. He's awaiting trial. The bragging was evidence.",tags:["manipulation","arrested"],type:"hack",
valueProposition:"Mango offered perpetual futures trading on Solana with good UX and deep liquidity. Margin trading, lending, and leveraged positions made it the go-to for Solana degens. At peak, significant TVL and trading volume.",
whatWentRight:["Good UX for perps trading","Deep liquidity for Solana ecosystem","Innovative margin system","Strong community of traders"],
whatWentWrong:["Single oracle source for price feeds","No circuit breakers on extreme price moves","Collateral valuation used manipulable spot price","Governance token ($MNGO) could be used as collateral","No monitoring for market manipulation patterns"],
theAlpha:["Oracle manipulation is existential risk for perps/lending","Multi-oracle systems reduce manipulation risk","Circuit breakers on price moves are essential","Governance tokens as collateral is dangerous","If you exploit a protocol, don't brag about it publicly"],
keyPeople:[{role:"Exploiter",name:"Avraham Eisenberg (arrested)"},{role:"Protocol",name:"Mango Markets DAO"}],
lessons:["Oracle manipulation can drain entire protocols","Multi-source oracles reduce single point of failure","Circuit breakers should pause on anomalous price action","Bragging about exploits attracts prosecution","'Legal market manipulation' is not a defense in court"],phoenix:{enabled:false}},

{id:27,name:"Badger DAO",category:"DeFi",launchDate:"2020-12",deathDate:"2021-12",amount:120000000,description:"Frontend attack via compromised Cloudflare. Users approved drains.",fullDescription:"Badger built 'Bitcoin DeFi' - vaults and strategies for BTC holders to earn yield. Hackers compromised Badger's Cloudflare API key and injected malicious scripts into the frontend that prompted users to approve unlimited token transfers.",causeOfDeath:"For weeks, users visiting the real Badger website were served malicious code. When they interacted with the site, they unknowingly approved transactions draining their wallets. $120M stolen from users who thought they were using the legitimate protocol.",tags:["hack","frontend"],type:"hack",
valueProposition:"Badger addressed real demand: Bitcoin holders wanted yield without selling BTC. Vaults automatically deployed wrapped BTC into yield strategies. The DAO structure and governance seemed decentralized and trustworthy.",
whatWentRight:["Identified real demand (yield on BTC)","Built functional BTC yield products","Strong DAO governance and community","Transparent on-chain operations"],
whatWentWrong:["Frontend security was an afterthought","Single API key compromise = total frontend control","No detection of malicious script injection","Users can't distinguish real site from compromised site","Web2 infrastructure (Cloudflare) was weak point"],
theAlpha:["Frontend attacks bypass all smart contract security","Users can't tell if a website is serving malicious code","Web2 infrastructure is the weak link in Web3","Always verify what you're signing - read the transaction","Hardware wallet prompts are your last line of defense"],
keyPeople:[{role:"Protocol",name:"Badger DAO"},{role:"Attack Vector",name:"Cloudflare API key"},{role:"Victims",name:"Active Badger users"}],
lessons:["Smart contract security doesn't protect against frontend attacks","Compromised CDN = compromised everything","Check what your wallet is asking you to approve","Unlimited approvals are dangerous - use limited amounts","The frontend is a trust assumption most people ignore"],phoenix:{enabled:false}}
];

const hallOfShame = [
{rank:1,id:'do-kwon',name:"Do Kwon",project:"Terra/LUNA",year:"2022",status:"Extradited to US",
extracted:"Unknown",peakMC:"$40B",victimLosses:"$40B+",
photoUrl:"images/do_kwon.jpg",viralQuote:"I don't debate the poor.",
viralMoment:"Arrogant tweets aged catastrophically as LUNA crashed from $119 to $0.00001.",
story:"Built Terra while mocking critics. When UST collapsed, tweets became evidence of hubris. Arrested with fake passports.",
tags:["terra","arrogance"],viralityScore:10,videoId:"KYlNI8U9TCw",videoType:"youtube"},

{rank:2,id:'sbf',name:"Sam Bankman-Fried",project:"FTX",year:"2022",status:"25 years prison",
extracted:"$8B+",peakMC:"$32B",victimLosses:"$8B+",
photoUrl:"images/sam_bankman_fried.jpg",viralQuote:"I didn't knowingly commingle funds.",
viralMoment:"Played League during investor calls while stealing $8B.",
story:"Built $32B empire while stealing deposits. Gave interviews playing games post-collapse. 25 years.",
tags:["ftx","fraud"],viralityScore:10,videoId:"20BEJouWBgY",videoType:"youtube"},

{rank:3,id:'su-zhu',name:"Su Zhu & Kyle Davies",project:"Three Arrows Capital",year:"2022",status:"Su Zhu arrested",
extracted:"$18B collapse",peakMC:"$18B AUM",victimLosses:"$3.5B+",
photoUrl:"images/_3_Su_Zhu___Kyle_Davies.jpg",viralQuote:"We are communicating with relevant parties.",
viralMoment:"Lost $18B, ghosted creditors, fled on yacht, launched exchange for bankruptcy claims.",
story:"Borrowed without collateral. LUNA destroyed them. Fled on yacht. Su Zhu arrested.",
tags:["3ac","yacht"],viralityScore:9,videoId:"7SaHu3UVNCk",videoType:"youtube"},

{rank:4,id:'mashinsky',name:"Alex Mashinsky",project:"Celsius",year:"2022",status:"Arrested",
extracted:"$10M+",peakMC:"$12B deposits",victimLosses:"$4.7B",
photoUrl:"images/_4_Alex_Mashinsky.jpg",viralQuote:"Banks are not your friends!",
viralMoment:"Weekly AMAs attacking banks while withdrawing $10M before freeze.",
story:"Working-class hero act while gambling funds. Withdrew $10M before freeze. Arrested.",
tags:["celsius","hypocrisy"],viralityScore:9,videoId:"dv6_57Bowhs",videoType:"youtube"},

{rank:5,id:'richard-heart',name:"Richard Heart",project:"HEX/PulseChain",year:"2023",status:"SEC charged, fugitive",
extracted:"$12B+ sacrifices",peakMC:"$12B",victimLosses:"Unknown",
photoUrl:"images/_5_Richard_Heart.png",viralQuote:"Delayed gratification is key.",
viralMoment:"$100M in watches while telling followers to 'sacrifice' to him.",
story:"Cult following. Billions in 'sacrifices'. SEC charged. Fled to Europe.",
tags:["hex","cult"],viralityScore:8,videoId:"NPVOxgqKZsI",videoType:"youtube"},

{rank:6,id:'ruja',name:"Dr. Ruja Ignatova",project:"OneCoin",year:"2017",status:"FBI Top 10 Wanted",
extracted:"$4B+",peakMC:"N/A",victimLosses:"$4B+",
photoUrl:"images/_6_Dr__Ruja_Ignatova.jpg",viralQuote:"Nobody will talk about Bitcoin!",
viralMoment:"Stadium events for fake crypto. No blockchain. Vanished 2017.",
story:"'Crypto Queen' sold fake crypto. No blockchain existed. $250K FBI reward.",
tags:["onecoin","fbi"],viralityScore:10,videoId:"ZoklPHEjXl4",videoType:"youtube"},

{rank:7,id:'africrypt',name:"Cajee Brothers",project:"Africrypt",year:"2021",status:"Fugitives",
extracted:"69,000 BTC",peakMC:"N/A",victimLosses:"$3.6B",
photoUrl:"images/_7_Cajee_Brothers.jpg",viralQuote:"Don't report to authorities.",
viralMoment:"Ages 18 and 21, vanished with 69K BTC after telling investors NOT to call police.",
story:"'AI trading' claims. 69K BTC accumulated. Said don't report 'hack'. Vanished.",
tags:["exit-scam"],viralityScore:8,videoId:"_T4OyfUoJ1I",videoType:"youtube"},

{rank:8,id:'bitconnect',name:"Satish Kumbhani",project:"BitConnect",year:"2018",status:"Indicted, hiding",
extracted:"$2.4B",peakMC:"$3.5B",victimLosses:"$2.4B",
photoUrl:"images/_8_Satish_Kumbhani.jpg",viralQuote:"BitConnect is the future!",
viralMoment:"Carlos Matos 'BITCONNEEECT!' - crypto's most legendary meme.",
story:"1% daily via fake bot. Carlos Matos meme. BCC crashed $400 to $1.",
tags:["ponzi","meme"],viralityScore:10,videoId:"gHdasR7PxW8",videoType:"youtube"},

{rank:9,id:'thodex',name:"Faruk Fatih Özer",project:"Thodex",year:"2021",status:"11,196 years prison",
extracted:"$2B",peakMC:"N/A",victimLosses:"$2B",
photoUrl:"images/_9_Faruk_Fatih_Özer.jpg",viralQuote:"Partnership negotiations.",
viralMoment:"Posted about negotiations while fleeing with $2B.",
story:"Turkey's largest exchange. Fled to Albania with $2B. 11,196 years.",
tags:["exit-scam","turkey"],viralityScore:8,videoId:"JWApzXk745Q",videoType:"youtube"},

{rank:10,id:'quadriga',name:"Gerald Cotten",project:"QuadrigaCX",year:"2019",status:"Dead (disputed)",
extracted:"$190M",peakMC:"N/A",victimLosses:"$190M",
photoUrl:"images/_10_Gerald_Cotten.jpg",viralQuote:"Only I have the passwords.",
viralMoment:"Sole keyholder 'died' in India. Wallets were already empty.",
story:"Canada's exchange. Died, cremated quick. Wallets empty for months. Many think faked.",
tags:["fake-death"],viralityScore:9,videoId:"HqmS-2D7SVM",videoType:"youtube"}
];

const pumpFunHorrors = [
{id:'baby',name:"The Baby Incident",perpetrator:"Mikael Owns",date:"2024",wtfFactor:10,emoji:"👶🔥",
extracted:"~$30K",peakMC:"Unknown",
shortDescription:"Tied up baby on stream. Got Pump.fun livestreams banned forever.",
fullStory:"Appeared with restrained infant during launch. Massive outrage. Pump.fun disabled all streams.",
aftermath:"Streams disabled permanently. Mikael vanished.",
tags:["banned"],videoId:"ZRWkTFqkhgY",videoType:"youtube"},

{id:'fire',name:"Fire Guy",perpetrator:"Anonymous",date:"2024",wtfFactor:9,emoji:"🔥😱",
extracted:"~$15K",peakMC:"Unknown",
shortDescription:"Set himself on fire to pump token.",
fullStory:"Doused with flammable liquid. Ignited on stream. Token pumped. Then rugged.",
aftermath:"Clip viral. Condition unknown.",tags:["fire"],videoId:"",videoType:"twitter-search"},

{id:'cereal',name:"Cereal Rugger",perpetrator:"Anonymous",date:"2024",wtfFactor:7,emoji:"🥣😐",
extracted:"~$50K",peakMC:"Unknown",
shortDescription:"Ate cereal calmly while rugging mid-bite.",
fullStory:"Said nothing. Ate cereal. Token pumped. Mid-bite, pulled liquidity.",
aftermath:"Became meme. Token zero.",tags:["cereal"],videoId:"",videoType:"twitter-search"},

{id:'classroom',name:"Classroom Launch",perpetrator:"Teen",date:"2024",wtfFactor:8,emoji:"🏫📱",
extracted:"~$10K",peakMC:"Unknown",
shortDescription:"Launched and rugged from school classroom.",
fullStory:"Streamed under desk while teacher lectured. Rugged before bell.",
aftermath:"Unknown if caught.",tags:["school"],videoId:"",videoType:"twitter-search"},

{id:'grandma',name:"Grandma Rugger",perpetrator:"Anonymous",date:"2024",wtfFactor:7,emoji:"👵💸",
extracted:"~$20K",peakMC:"Unknown",
shortDescription:"Brought confused grandma. Rugged with her on screen.",
fullStory:"Grandma smiled and waved. Chat pumped. Grandson rugged.",
aftermath:"Grandma still confused.",tags:["grandma"],videoId:"",videoType:"twitter-search"},

{id:'mando',name:"Mando's Stunts",perpetrator:"Mando",date:"2024",wtfFactor:9,emoji:"🎭🤯",
extracted:"$100K+",peakMC:"Various",
shortDescription:"Serial streamer. Pump.fun's biggest winner.",
fullStory:"Constantly one-upped stunts. Each clip viral. $100K+ extracted.",
aftermath:"Still active. Platform's poster child.",tags:["stunts"],videoId:"gKHJYuG4yFQ",videoType:"youtube"}
];

const trenchLegends = [
{id:'quant-kid',name:"Quant Kid",perpetrator:"13-year-old",project:"Gen Z Quant",date:"2024",wtfFactor:10,emoji:"👦😭",
extracted:"~$30K",peakMC:"$85M (revenge pump)",victimLosses:"Unknown",
blockchain:"Solana",contractAddress:"3an8rhdepsLCya22af7qDBKPbdomw8K4iCHXaA2Gpump",
shortDescription:"13yo rugged $30K. Community revenge-pumped to $85M. Cried 'I'm just a kid!'",
fullStory:"Livestreamed launch. Extracted $30K. Cried when confronted. Community pumped to $85M to spite him.",
aftermath:"Doxxed. Launched 2 more tokens, rugged those too.",
tags:["teen"],photoUrl:"images/quant.jpg",videoId:"jZUeyFKw7u4",videoType:"youtube"},

{id:'hawk-tuah',name:"Hawk Tuah Token",perpetrator:"Haliey Welch",project:"HAWK",date:"2024",wtfFactor:9,emoji:"🦅💀",
extracted:"~$1.27M (insiders)",peakMC:"$490M",victimLosses:"Millions",
blockchain:"Solana",contractAddress:"HAWKThXRcNL9ZGZKqgUXLm4W8tnRZ7U6MVdEepSutj34",
shortDescription:"$490M in 15 min. Insiders dumped. Crashed 93%. Lawsuit filed.",
fullStory:"Viral meme girl's token. $490M in minutes. Insiders dumped $1.27M. She got $125K+ fee.",
aftermath:"Class action lawsuit. Added as defendant.",
tags:["celebrity"],photoUrl:"images/Hawk_Tuah_Token.jpg",videoId:"qwQTX2vbgRk",videoType:"youtube"},

{id:'squid',name:"Squid Game Token",perpetrator:"Anonymous",project:"SQUID",date:"2021",wtfFactor:10,emoji:"🦑🎮",
extracted:"~$3.38M",peakMC:"$2,860/token",victimLosses:"$3.38M+",
blockchain:"BSC",contractAddress:"0x87230146E138d3F296a9a77e497A2A83012e9Bc5",
shortDescription:"45,000% pump. Couldn't sell - honeypot. Crashed to $0 in 5 min.",
fullStory:"No Netflix affiliation. Pumped 45,000%. Contract prevented selling. Classic honeypot.",
aftermath:"Textbook honeypot example.",
tags:["honeypot"],photoUrl:"images/Squid_Game_Token.jpg",videoId:"CpR2kMxy7O8",videoType:"youtube"},

{id:'anubis',name:"AnubisDAO",perpetrator:"Beerus",project:"ANKH",date:"2021",wtfFactor:9,emoji:"🐺💨",
extracted:"$60M",peakMC:"$60M",victimLosses:"$60M",
blockchain:"Ethereum",contractAddress:"0x38a0df9a08d18dc06cd91fc7ec94a0acdf28d994",
shortDescription:"$60M raised in 20 hours. Drained same day. Fastest major rug.",
fullStory:"OHM fork. $60M in 20 hours. All ETH transferred out same day. 'Phishing' excuse.",
aftermath:"ZachXBT traced funds. Fastest large rug ever.",
tags:["speedrun"],videoId:"97bHgDkf3pE",videoType:"youtube"},

{id:'faze',name:"FaZe Save The Kids",perpetrator:"FaZe Kay",project:"$KIDS",date:"2021",wtfFactor:8,emoji:"🎮🤑",
extracted:"~$30K",peakMC:"~$2-3M",victimLosses:"Hundreds of thousands",
blockchain:"BSC",contractAddress:"0x7acf49997e9598843cb9051389fa755969e551bb",
shortDescription:"Gaming influencers scammed teen fans with 'charity' token.",
fullStory:"50M+ followers. Anti-whale code secretly changed. Kay dumped. Coffeezilla exposed.",
aftermath:"Kay fired. Paid $400-500K refunds.",
tags:["influencer"],photoUrl:"images/FaZe_Save_The_Kids.png",videoId:"6fxtayFVwxQ",videoType:"youtube"},

{id:'ice',name:"Ice Poseidon",perpetrator:"Paul Denino",project:"CxCoin",date:"2022",wtfFactor:10,emoji:"🎥💩",
extracted:"$500K",peakMC:"Unknown",victimLosses:"$500K",blockchain:"Ethereum",
shortDescription:"Admitted on camera: 'I just didn't care.' Zero consequences.",
fullStory:"Raised $500K. Coffeezilla confronted. Openly admitted didn't care about investors.",
aftermath:"No legal consequences. Still streams.",
tags:["confession"],photoUrl:"images/ice_pos.jpg",videoId:"3NA8Ee3RF5E",videoType:"youtube"},

{id:'evil-ape',name:"Evil Ape",perpetrator:"Evil Ape",project:"Evolved Apes",date:"2021",wtfFactor:7,emoji:"🦍😈",
extracted:"$2.7M",peakMC:"$2.7M",victimLosses:"$2.7M",blockchain:"Ethereum",
shortDescription:"Named himself 'Evil Ape'. People trusted him. He rugged.",
fullStory:"NFT project. Dev literally called Evil Ape. Drained 798 ETH. Game never made.",
aftermath:"Community tried 'Fight Back Apes'. Never caught.",
tags:["nft"],photoUrl:"images/Evil_Ape.jpg",videoId:"jLBvfEdxjYU",videoType:"youtube"}
];

const typeLabels = {rug:"RUG PULL",hack:"HACKED",collapse:"COLLAPSED"};
const typeColors = {rug:"#ff2d55",hack:"#ff9500",collapse:"#bf5af2"};
