// CRYPTO GRAVEYARD v5.0 - Phoenix Protocol Edition (Expanded)
const BAGS_REFERRAL = "https://bags.fm/?ref=cryptograveyrd";

const cryptoCorpses = [
{id:1,name:"Internet Computer (ICP)",category:"L1 Blockchain",launchDate:"2021-05",deathDate:"2021-05",amount:45000000000,description:"Launched at $750, crashed to $3. Insiders dumped on retail.",fullDescription:"Dfinity's Internet Computer launched with unprecedented hype, reaching $45 billion on day one.",causeOfDeath:"VCs who got tokens at cents dumped immediately. Price crashed 99.5%. Retail bought the top while insiders exit-liquified.",tags:["insider-dump","vc-exit"],type:"collapse",
valueProposition:"Dfinity promised to replace AWS/GCP with decentralized cloud computing. The tech was genuinely innovative - canister smart contracts, reverse gas model, web-speed finality.",
whatWentRight:["Genuinely innovative canister smart contract architecture","Web-speed transaction finality achieved","Strong academic credentials and research","Decentralized compute is a real market need"],
whatWentWrong:["VCs got tokens at $0.03, dumped at $750","Token unlock schedule was predatory","Marketing created unrealistic expectations","Retail had no chance against insider selling"],
theAlpha:["Check unlock schedules before buying ANYTHING","VC entry prices vs retail prices = guaranteed dump","Good tech doesn't save bad tokenomics","Launch valuations represent peak delusion"],
keyPeople:[{role:"Founder",name:"Dominic Williams"},{role:"Investor",name:"Andreessen Horowitz"},{role:"Investor",name:"Polychain Capital"}],
lessons:["Check unlock schedules before buying ANYTHING","Launch valuations represent peak delusion, not value","VC entry prices vs retail prices = guaranteed dump","Good tech doesn't save bad tokenomics","Always check who can sell before you buy"],
phoenix:{enabled:true,score:{rebuild:4,market:5,fairLaunch:5},
valueProposition:"Dfinity promised to replace AWS/GCP with decentralized cloud computing. The tech was genuinely innovative - canister smart contracts, reverse gas model, web-speed finality. Enterprise adoption was actually growing before the dump destroyed trust.",
theAlpha:["Decentralized compute is a real and growing need","AI boom creating massive GPU/compute demand","Canister smart contracts were genuinely innovative","VC dumps killed trust, not the underlying technology","100% fair launch eliminates the dump problem entirely"],
keyPeople:[{role:"Founder",name:"Dominic Williams"},{role:"Investor",name:"Andreessen Horowitz"},{role:"Investor",name:"Polychain Capital"}],
marketToday:"Cloud computing is $500B+ market. AWS/GCP dominate with 60%+ margins. AI compute demand exploding - GPU costs up 300% since ChatGPT. Decentralized alternatives gaining traction: Akash, Render, io.net.",
protocols:["Akash","Render","io.net","Golem"],
concept:{name:"COMPUTE FAIR",tagline:"The cloud that can't dump on you",description:"Decentralized GPU compute network. 100% fair launch - zero VC tokens. Node operators provide GPUs, earn fees. Users pay 40-60% less than AWS for AI inference. Community owns the infrastructure."},
executionPlan:["Launch node operator program - target 100 GPUs month one","Build simple API matching AWS/GCP for easy migration","Fair launch token on Bags - earned by operators and users","Focus on AI inference market first","Scale to training workloads after proving reliability"],
tokenomics:"100% fair launch. No team tokens, no VC allocation. Earned through: providing compute (70%), using compute (20%), governance (10%). Revenue from fees to stakers.",
monetization:"10% platform fee on compute transactions. At 1000 GPUs doing $100/day = $3.65M/year protocol revenue distributed to token holders.",
risks:["Cold start problem - need supply and demand simultaneously","Nvidia/cloud provider moats are strong","Decentralized compute UX historically poor"]}},

{id:2,name:"Terra/LUNA",category:"L1 Blockchain",launchDate:"2018-04",deathDate:"2022-05",amount:40000000000,description:"Algorithmic stablecoin death spiral wiped out $40B.",fullDescription:"Terra was built around UST, an algorithmic stablecoin. 20% APY on Anchor attracted massive deposits.",causeOfDeath:"UST lost peg, algorithm minted trillions of LUNA trying to defend. LUNA crashed from $119 to $0.00001 in days. The 20% yield was subsidized - reserves depleted, spiral began.",tags:["death-spiral","stablecoin"],type:"collapse",
valueProposition:"Terra offered a decentralized stablecoin with 20% yield, simple UX, and integration across 100+ apps. UST reached $18B market cap proving massive demand.",
whatWentRight:["$18B UST market cap proved demand for decentralized stables","Simple UX attracted millions of non-DeFi users","Ecosystem of 100+ integrated apps","Fast, cheap transactions on Terra chain"],
whatWentWrong:["Algorithmic stability without sufficient collateral","20% yield was subsidized, not sustainable","Arrogant leadership dismissed valid criticism","No circuit breakers for death spiral"],
theAlpha:["Decentralized stablecoins have massive demand","Over-collateralization is non-negotiable","Real yield must come from real economic activity","Simple UX can attract mainstream users"],
keyPeople:[{role:"Founder",name:"Do Kwon"},{role:"Founder",name:"Daniel Shin"},{role:"Investor",name:"Pantera Capital"},{role:"Investor",name:"Galaxy Digital"}],
lessons:["Algorithmic stables without collateral are fragile","20% 'stable' yield is always a red flag","Reflexive mechanisms spiral both directions","150%+ collateralization needed for survival","Arrogance is a red flag in founders"],
phoenix:{enabled:true,score:{rebuild:4,market:5,fairLaunch:4},
valueProposition:"Terra proved massive demand exists for decentralized stablecoins - UST hit $18B market cap. Simple 'deposit and earn' UX attracted non-crypto natives. Ecosystem integration across 100+ apps made it sticky.",
theAlpha:["$18B UST at peak proved decentralized stable demand","Simple UX attracted millions of non-DeFi users","The PROBLEM was undercollateralization, not the concept","Over-collateralized designs (DAI, LUSD) survived the crash","Real 5-8% yield is achievable from actual DeFi activity"],
keyPeople:[{role:"Founder",name:"Do Kwon"},{role:"Founder",name:"Daniel Shin"},{role:"Investor",name:"Pantera Capital"},{role:"Investor",name:"Galaxy Digital"}],
marketToday:"Stablecoin market is $150B+ and growing. USDT/USDC dominate but are centralized - Tether froze $1B+ in 2023. Gap for decentralized, over-collateralized stable with sustainable yield. Ethena's USDe showing demand.",
protocols:["MakerDAO","Liquity","Ethena","Frax"],
concept:{name:"FORTRESS",tagline:"The stablecoin that survives the next crash",description:"150%+ over-collateralized stablecoin backed by diversified crypto. Sustainable 5-7% APY from real sources: Aave lending, Uniswap LP fees, liquid staking. No algorithmic minting. No fake APY. Just math that works."},
executionPlan:["Launch with ETH/stETH collateral vaults at 150% minimum","Yield aggregation from Aave, Compound, Lido","MEV-protected liquidation engine","Fair launch governance on Bags - no VC allocation","Cross-chain expansion after $50M TVL"],
tokenomics:"Governance token fair launched. No yield from inflation. Protocol fees (0.5% mint/redeem) distributed to stakers. Emergency shutdown controlled by governance.",
monetization:"0.5% fee on mint/redeem, 10% of yield generated. At $100M TVL with 6% yield = $600K/year protocol revenue.",
risks:["Smart contract risk on yield sources","Collateral price crashes in black swan","Competition from established players like MakerDAO"]}},

{id:3,name:"FTX",category:"Exchange",launchDate:"2019-05",deathDate:"2022-11",amount:32000000000,description:"SBF stole $8B customer funds. 25 years prison.",fullDescription:"FTX became the third-largest crypto exchange with $32B valuation. SBF was on magazine covers, meeting world leaders, and donating to politicians. Behind the scenes, he secretly funneled customer deposits to his hedge fund Alameda Research.",causeOfDeath:"CoinDesk exposed Alameda's balance sheet was mostly FTT tokens. Binance's CZ triggered a bank run. Within days, $6B withdrawal requests revealed an $8B hole. SBF arrested in Bahamas, extradited, sentenced to 25 years.",tags:["fraud","customer-funds"],type:"rug",
valueProposition:"FTX offered superior trading UX, innovative products like prediction markets, and aggressive user acquisition. It seemed like the 'adult in the room' - regulated, mainstream, endorsed by celebrities.",
whatWentRight:["Best-in-class trading interface and mobile app","Innovative products (prediction markets, tokenized stocks)","Strong brand building and mainstream recognition","Regulatory engagement appeared serious"],
whatWentWrong:["Zero separation between exchange and trading firm","Customer funds treated as company money","No real board oversight or governance","FTT token used as collateral was circular","Accounting was literally done in QuickBooks"],
theAlpha:["Charismatic founders can hide massive fraud","Regulation theater isn't real regulation","Proof of reserves should be standard","Celebrity endorsements mean nothing about safety","If an exchange has a token, be skeptical"],
keyPeople:[{role:"Founder/CEO",name:"Sam Bankman-Fried"},{role:"Co-founder",name:"Gary Wang"},{role:"CEO Alameda",name:"Caroline Ellison"},{role:"Investor",name:"Sequoia Capital"},{role:"Investor",name:"Paradigm"}],
lessons:["Not your keys, not your coins - even on 'reputable' exchanges","Proof of reserves should be mandatory and real-time","Charismatic CEOs are marketing, not security","Effective altruism can be cover for fraud","Celebrity endorsements mean nothing"],
phoenix:{enabled:false}},

{id:4,name:"Three Arrows Capital",category:"Hedge Fund",launchDate:"2012-01",deathDate:"2022-07",amount:18000000000,description:"Overleveraged hedge fund collapsed, contagion spread everywhere.",fullDescription:"3AC was crypto's most respected hedge fund, managing $18B at peak. Su Zhu and Kyle Davies borrowed billions from every major lender without posting adequate collateral. They made massive concentrated bets on LUNA, stETH, and GBTC.",causeOfDeath:"LUNA collapse destroyed 3AC's largest position. stETH depeg locked billions. They ghosted creditors, fled Singapore on a yacht, and left a trail of bankruptcies including Voyager, Celsius, and BlockFi.",tags:["leverage","contagion"],type:"collapse",
valueProposition:"3AC positioned itself as the smart money - early investors in major protocols with a strong track record. Lenders competed to give them capital with minimal collateral requirements.",
whatWentRight:["Early investments in Solana, Avalanche, Luna paid off massively","Built reputation as sophisticated crypto-native fund","Strong industry relationships","Correctly identified major trends early"],
whatWentWrong:["Borrowed without adequate collateral across dozen+ lenders","Concentrated bets with no hedging","No risk management or position limits","Ghosted creditors instead of negotiating","Founders' arrogance ('supercycle' thesis)"],
theAlpha:["Even 'smart money' can blow up spectacularly","Lending without collateral is just gambling","Concentrated positions amplify both gains and losses","When hedge funds ghost you, they're already insolvent","Contagion in crypto is severe - one failure cascades"],
keyPeople:[{role:"Co-founder",name:"Su Zhu"},{role:"Co-founder",name:"Kyle Davies"},{role:"Creditor",name:"Genesis"},{role:"Creditor",name:"Voyager"},{role:"Creditor",name:"BlockFi"}],
lessons:["Excessive leverage amplifies losses catastrophically","Reputation doesn't equal solvency","Counterparty risk can cascade across entire industry","When whales go silent, assume the worst","Never lend without adequate collateral"],
phoenix:{enabled:false}},

{id:5,name:"Anchor Protocol",category:"DeFi",launchDate:"2021-03",deathDate:"2022-05",amount:17000000000,description:"20% stable yield attracted $17B. Unsustainable subsidies killed Terra.",fullDescription:"Anchor offered 20% APY on UST deposits - far above any sustainable rate. At peak, it held $17B in deposits. The yield was subsidized by Terra's reserves at a burn rate of $5M per day.",causeOfDeath:"When reserves ran low, confidence cracked. Withdrawals exceeded deposits. UST lost peg. The death spiral that killed Terra/LUNA began on Anchor.",tags:["unsustainable-yield","terra"],type:"collapse",
valueProposition:"Anchor promised stable, high yield on stablecoins - the holy grail of DeFi. Simple deposit-and-earn UX made it accessible to non-crypto natives.",
whatWentRight:["Simple UX attracted billions in deposits","Integrated seamlessly with Terra ecosystem","20% APY was compelling marketing","Proved demand for stable yield products"],
whatWentWrong:["20% yield was subsidized, not earned","No sustainable revenue model","Reserves depleting at $5M/day","Created false sense of security","Yield came from inflation, not productivity"],
theAlpha:["Sustainable DeFi yield is 3-8%, not 20%","If you can't identify the yield source, you're the yield","Subsidized growth isn't real product-market fit","Simple UX can hide broken economics","Always ask: where does the money come from?"],
keyPeople:[{role:"Creator",name:"Terraform Labs"},{role:"Founder",name:"Do Kwon"},{role:"Auditor",name:"Various (all missed the risk)"}],
lessons:["20% stable yield is mathematically impossible long-term","Subsidized yield isn't real - it's marketing spend","Check where yield actually comes from","Simple UX can hide fundamentally broken mechanics","If it seems too good to be true, it is"],
phoenix:{enabled:false}},

{id:6,name:"Celsius Network",category:"CeFi Lending",launchDate:"2017-06",deathDate:"2022-07",amount:12000000000,description:"18% yields while secretly gambling funds. CEO arrested.",fullDescription:"Celsius offered up to 18% APY while CEO Mashinsky attacked traditional banks in weekly AMAs. Behind the scenes, customer funds were gambled on risky DeFi plays, staked in illiquid positions, and lost in hacks.",causeOfDeath:"Froze $8B in withdrawals as liquidity crisis hit. $1.2B hole revealed. Mashinsky had withdrawn $10M before the freeze. Arrested for fraud. Users lost billions.",tags:["fraud","yield-fraud"],type:"rug",
valueProposition:"Celsius offered high yields on crypto deposits with a simple mobile app. 'Unbank yourself' messaging resonated with crypto natives tired of 0% bank rates.",
whatWentRight:["Simple mobile UX attracted millions of users","Strong community and brand loyalty","'Unbank yourself' message resonated","Demonstrated demand for yield on crypto"],
whatWentWrong:["Yields funded by risky DeFi gambling","No transparency on fund deployment","CEO withdrew millions before freeze","Staked ETH in illiquid positions","Lost $50M+ in various hacks"],
theAlpha:["CeFi opacity enables fraud","Yields above market rate = hidden risk","Charismatic CEOs are red flags, not features","If you don't control keys, you don't control crypto","Watch insider transactions, not marketing"],
keyPeople:[{role:"Founder/CEO",name:"Alex Mashinsky"},{role:"CFO",name:"Shlomi Leon"},{role:"Investor",name:"WestCap"},{role:"Investor",name:"Caisse de dépôt"}],
lessons:["Yields above market rate mean hidden risk","CeFi opacity enables fraud","Charismatic CEOs are red flags not features","If you don't control keys, you don't control crypto","Watch what insiders do, not what they say"],
phoenix:{enabled:true,score:{rebuild:4,market:4,fairLaunch:5},
valueProposition:"Celsius proved users genuinely want yield on idle crypto. Simple mobile UX attracted millions of non-DeFi users. 'Unbank yourself' messaging resonated. At peak, $25B+ in assets under management.",
theAlpha:["Users genuinely want yield on idle crypto","Simple mobile UX attracted millions","Problem was opacity and fraud, not the concept","Decentralized lending works - Aave has $10B+ TVL","Trust through transparency, not charisma"],
keyPeople:[{role:"Founder",name:"Alex Mashinsky"},{role:"Investor",name:"WestCap"},{role:"Investor",name:"CDPQ"},{role:"Investor",name:"Tether"}],
marketToday:"CeFi lending is dead - BlockFi, Celsius, Voyager all bankrupt. DeFi lending thriving but complex for normies. Aave, Compound have billions but require wallet setup, gas management. Gap: Aave-level security with Celsius-level UX.",
protocols:["Aave","Compound","Morpho","Spark"],
concept:{name:"GLASS VAULT",tagline:"See everything. Trust nothing. Earn anyway.",description:"Non-custodial lending aggregator with radical transparency. Your keys, always. Real-time dashboard showing exactly where funds are deployed. No black box. Yield from battle-tested protocols only. Mobile app simplicity, DeFi security."},
executionPlan:["Build non-custodial vault contracts - users always control withdrawal","Integrate with Aave, Compound, Morpho - only battle-tested protocols","Real-time transparency dashboard - every position visible","Mobile app with one-tap deposit/withdraw","Fair launch governance on Bags"],
tokenomics:"Governance token controls fee switch and strategy allocation. 0.1% management fee on TVL distributed to stakers. No yield from inflation - pure revenue share.",
monetization:"0.1% annual fee on TVL + 5% of yield generated. At $500M TVL earning 5% = $1.75M/year protocol revenue.",
risks:["Smart contract risk on underlying protocols","Yield compression over time","Competition from protocol-native apps"]}},

{id:7,name:"BlockFi",category:"Lending",launchDate:"2017-08",deathDate:"2022-11",amount:10000000000,description:"Hit by 3AC, then 'rescued' by FTX with stolen funds.",fullDescription:"BlockFi was a regulated crypto lender offering yield accounts. Hit hard by 3AC default, they accepted an FTX rescue package. When FTX collapsed, BlockFi discovered their savior had paid with stolen customer funds.",causeOfDeath:"Double-victimized: first by 3AC default, then by FTX collapse. The FTX 'rescue' loan came from stolen customer deposits. Filed bankruptcy within weeks of FTX collapse.",tags:["contagion","ftx"],type:"collapse",
valueProposition:"BlockFi offered regulated, compliant crypto yield products. Interest accounts, crypto-backed loans, and trading - positioned as the safe, institutional choice.",
whatWentRight:["Regulatory compliance efforts were genuine","Institutional-grade security practices","Strong brand among conservative crypto investors","Transparent about some risks"],
whatWentWrong:["Lent to 3AC without adequate collateral","Accepted FTX rescue without due diligence","Concentrated counterparty risk","Being regulated didn't prevent insolvency"],
theAlpha:["Regulation doesn't equal safety","Counterparty risk can come from rescuers","Due diligence on partners is critical","Concentrated lending exposure is dangerous","Even 'safe' players can fail spectacularly"],
keyPeople:[{role:"Founder/CEO",name:"Zac Prince"},{role:"Co-founder",name:"Flori Marquez"},{role:"Creditor",name:"3AC"},{role:"Rescuer",name:"FTX"}],
lessons:["Counterparty risk can come from rescuers too","Being regulated doesn't mean being safe","Due diligence on partners matters","Contagion can hit from multiple directions","There are no safe havens in systemic crises"],
phoenix:{enabled:false}},

{id:8,name:"Mt. Gox",category:"Exchange",launchDate:"2010-07",deathDate:"2014-02",amount:8500000000,description:"Lost 850,000 BTC. The original crypto catastrophe.",fullDescription:"Mt. Gox once handled 70% of all Bitcoin transactions. Founded as a Magic: The Gathering trading site, it pivoted to Bitcoin. Years of security breaches went unnoticed as hackers slowly drained funds.",causeOfDeath:"850,000 BTC (worth $450M then, $50B+ at peak) stolen over years. CEO Mark Karpeles discovered empty wallets. Creditors waited 10+ years for partial recovery.",tags:["hack","legendary"],type:"hack",
valueProposition:"Mt. Gox was THE Bitcoin exchange - first mover advantage when there were no alternatives. Easy fiat on-ramp at a time when buying Bitcoin was extremely difficult.",
whatWentRight:["First major Bitcoin exchange","Made buying Bitcoin accessible","Handled massive volume growth","Created the exchange model others copied"],
whatWentWrong:["Security was an afterthought","No cold storage practices","Single point of failure architecture","CEO was a developer, not a security expert","Hack went undetected for years"],
theAlpha:["Not your keys, not your coins - the original lesson","Security must be priority #1 for exchanges","Cold storage is non-negotiable","Single points of failure are existential risks","Technical founders need security expertise"],
keyPeople:[{role:"Founder/CEO",name:"Mark Karpeles"},{role:"Original Creator",name:"Jed McCaleb"},{role:"Trustee",name:"Nobuaki Kobayashi"}],
lessons:["Not your keys, not your coins","Security cannot be an afterthought","Cold storage is essential for exchanges","First mover advantage doesn't guarantee survival","Verify exchange security practices"],
phoenix:{enabled:false}},

{id:9,name:"Voyager Digital",category:"Lending",launchDate:"2018-01",deathDate:"2022-07",amount:7000000000,description:"Lent $650M to 3AC unsecured. Falsely implied FDIC insurance.",fullDescription:"Voyager was a publicly traded crypto broker offering yield. They lent $650M to 3AC with minimal collateral. Marketing implied FDIC insurance covered crypto - it didn't.",causeOfDeath:"3AC default made the $650M loan unrecoverable. 3.5 million customers lost access to funds. FDIC sent cease-and-desist for misleading insurance claims.",tags:["3ac-exposure","bankruptcy"],type:"collapse",
valueProposition:"Voyager offered commission-free trading and competitive yields. Being publicly traded suggested legitimacy and oversight.",
whatWentRight:["User-friendly mobile app","Commission-free trading attracted users","Public company status suggested oversight","Competitive yield offerings"],
whatWentWrong:["$650M unsecured loan to single counterparty","Misleading FDIC insurance claims","No risk management on concentrated exposure","Public company oversight was insufficient","Trusted 3AC's reputation over collateral"],
theAlpha:["FDIC does not cover crypto - ever","Public company status doesn't ensure safety","Concentrated lending is existential risk","Reputation-based lending is dangerous","Read the fine print on insurance claims"],
keyPeople:[{role:"CEO",name:"Stephen Ehrlich"},{role:"Debtor",name:"3AC"},{role:"Regulator",name:"FDIC"}],
lessons:["FDIC does not cover crypto","Public company status doesn't mean safe","Concentrated counterparty risk is deadly","Read the fine print on insurance","Trust collateral, not reputation"],
phoenix:{enabled:false}},

{id:10,name:"Bitfinex Hack",category:"Exchange",launchDate:"2012-01",deathDate:"2016-08",amount:4500000000,description:"119,756 BTC stolen. Hackers were a married couple.",fullDescription:"Bitfinex lost 119,756 BTC in a sophisticated hack exploiting their multi-sig setup. The stolen Bitcoin sat dormant for years until hackers Ilya Lichtenstein and Heather Morgan tried to launder it.",causeOfDeath:"DOJ traced the funds through blockchain forensics. Arrested the married couple and seized $3.6B - the largest DOJ financial seizure ever. Heather was also a cringeworthy rapper ('Razzlekhan').",tags:["hack","recovered"],type:"hack",
valueProposition:"Bitfinex was a major exchange offering advanced trading features and high liquidity for serious traders.",
whatWentRight:["Bitfinex survived the hack (socialized losses)","Eventually recovered some funds","Blockchain transparency enabled tracing","DOJ seizure proved crypto isn't anonymous"],
whatWentWrong:["Multi-sig implementation was flawed","Security audit missed vulnerabilities","Hot wallet held too much value","Response was to socialize losses to users"],
theAlpha:["Stolen crypto can be traced and recovered","Blockchain transparency cuts both ways","Even sophisticated hackers get caught","Time doesn't make stolen coins safe","Multi-sig isn't automatically secure"],
keyPeople:[{role:"Hacker",name:"Ilya Lichtenstein"},{role:"Hacker",name:"Heather Morgan"},{role:"Exchange CEO",name:"JL van der Velde"}],
lessons:["Stolen crypto can be traced","Blockchain transparency is permanent","Even years later, hackers can be caught","Multi-sig requires proper implementation","Exchange hacks don't have to be fatal"],
phoenix:{enabled:false}},

{id:11,name:"Axie Infinity",category:"GameFi",launchDate:"2018-03",deathDate:"2022-06",amount:4200000000,description:"Play-to-earn became work-to-lose.",fullDescription:"Axie Infinity achieved 2.7 million daily users. Filipino players quit jobs to play full-time, earning more than minimum wage. The game required $1,000+ in NFTs to start and endless new players to sustain payouts.",causeOfDeath:"Ponzi dynamics collapsed when growth slowed. SLP token crashed 95%. Ronin bridge hack ($625M) was the killing blow. Players realized they were working for below minimum wage.",tags:["gamefi","ponzinomics"],type:"collapse",
valueProposition:"Axie proved crypto gaming could achieve mainstream adoption. Real income for players in developing countries. Cute monsters with genuine gameplay depth.",
whatWentRight:["2.7M daily users proved demand","Created real income for developing world players","Cute, engaging monster battling gameplay","Strong community and guild ecosystem","Mobile gaming done right"],
whatWentWrong:["$1,000+ barrier to entry was exclusionary","Two-token model created death spiral","Earning required constant new player growth","Game became work, not fun","Ronin bridge security was inadequate"],
theAlpha:["Crypto gaming demand is real and massive","Game must be fun WITHOUT earning","Free-to-play with optional earning works better","Two-token models are inherently unstable","Security of bridges is critical infrastructure"],
keyPeople:[{role:"Founder",name:"Trung Nguyen"},{role:"Founder",name:"Aleksander Larsen"},{role:"Investor",name:"Andreessen Horowitz"},{role:"Hacker",name:"Lazarus Group"}],
lessons:["Game must be fun WITHOUT earning","Play-to-earn requires infinite growth","Token emissions must tie to real revenue","Two-token models can spiral quickly","Bridge security is critical"],
phoenix:{enabled:true,score:{rebuild:5,market:5,fairLaunch:4},
valueProposition:"Axie proved crypto gaming could achieve mainstream adoption. 2.7 million daily users earning real income. Filipino players quit jobs to play full-time. The core insight was valid: people spend enormous time in games, so let them earn while playing.",
theAlpha:["2.7M daily users proved crypto gaming demand is REAL","Breeding mechanics created emotional attachment to NFTs","Community guilds showed power of coordinated play","Mobile gaming is $90B+ market barely touched by crypto","Battle mechanics were engaging - the game had real depth"],
keyPeople:[{role:"Founder",name:"Trung Nguyen"},{role:"Founder",name:"Aleksander Larsen"},{role:"Investor",name:"Andreessen Horowitz"},{role:"Investor",name:"Paradigm"}],
marketToday:"Gaming is a $200B+ industry. Mobile gaming alone is $90B. Play-to-earn is dead, but 'play-AND-earn' emerging. Successful examples: Pixels, Big Time. Gap: fair-launched mobile game where earning enhances fun.",
protocols:["Solana Gaming","Immutable X","Arbitrum Nova"],
concept:{name:"QUEST PROTOCOL",tagline:"The game you'd play even if tokens were worthless",description:"Mobile-first RPG where the core loop is genuinely fun. Tokens earned through gameplay but capped daily to prevent grinding culture. NFTs are cosmetic flexes, not pay-to-win. Revenue from battle passes and cosmetics - proven $50B+ market."},
executionPlan:["Build genuinely fun mobile game first - 3 month prototype with no crypto","Soft launch to test retention - target 20% Day-30 before adding tokens","Add optional token earning - capped at $5-10/day","Fair launch governance on Bags - earned through achievements","Revenue share to stakers from cosmetic sales"],
tokenomics:"Fixed 100M supply. No emissions - tokens from one-time achievement unlocks. Revenue from cosmetics: 70% to stakers, 20% treasury, 10% dev. 5% burn on cosmetic purchases.",
monetization:"Battle passes ($10/season), cosmetic NFTs ($1-100), tournament entry (5% rake). Target: $2 ARPU on 500K MAU = $1M/month to token holders.",
risks:["Mobile dev is expensive and competitive","Crypto gaming reputation damaged","App store NFT policies are restrictive"]}},

{id:12,name:"OneCoin",category:"Ponzi",launchDate:"2014-01",deathDate:"2017-10",amount:4000000000,description:"No blockchain existed. Crypto Queen vanished with $4B.",fullDescription:"Dr. Ruja Ignatova, the 'Crypto Queen,' promised OneCoin would surpass Bitcoin. She held stadium events, published fake trading volumes, and recruited via MLM. One problem: no blockchain ever existed.",causeOfDeath:"Ruja flew to Athens in October 2017 and vanished. FBI placed her on Top 10 Most Wanted with $250K reward. Her brother Konstantin arrested. Billions gone.",tags:["ponzi","fbi-wanted"],type:"rug",
valueProposition:"OneCoin marketed itself as 'Bitcoin killer' - easier to use, backed by a charismatic leader, with guaranteed returns. MLM structure made victims into recruiters.",
whatWentRight:["Masterful marketing and branding","Charismatic, credible-seeming leader","MLM structure created viral growth","Exploited crypto FOMO effectively"],
whatWentWrong:["No blockchain ever existed","Pure MLM recruitment scheme","Fake exchange with fake prices","Regulatory warnings ignored","Leader vanished with everything"],
theAlpha:["Verify the blockchain actually exists","MLM + crypto is always a scam","Charismatic leaders can be sociopaths","If you can't withdraw, it's not real","Stadium events are red flags, not validation"],
keyPeople:[{role:"Founder",name:"Dr. Ruja Ignatova"},{role:"Co-founder",name:"Konstantin Ignatov"},{role:"Status",name:"FBI Top 10 Most Wanted"}],
lessons:["Verify blockchain actually exists","MLM + crypto = guaranteed scam","Charismatic leaders aren't proof of legitimacy","If you can't verify on-chain, it's not crypto","Do your own research means actually researching"],
phoenix:{enabled:false}},

{id:13,name:"Olympus DAO",category:"DeFi",launchDate:"2021-03",deathDate:"2022-01",amount:4000000000,description:"(3,3) promised 7,000% APY. Game theory betrayed everyone.",fullDescription:"Olympus pioneered (3,3) game theory - if everyone stakes, everyone wins. At peak, OHM offered 7,000%+ APY through rebasing. Protocol-owned liquidity was genuinely innovative.",causeOfDeath:"When confidence cracked, game theory flipped to (-3,-3). Everyone unstaked and sold. OHM crashed from $1,400 to under $15 - a 99% collapse. Memes turned out not to be monetary policy.",tags:["ponzinomics","defi-2.0"],type:"collapse",
valueProposition:"Olympus offered mind-blowing APY through novel tokenomics. Protocol-owned liquidity solved mercenary capital problem. (3,3) meme created cult following.",
whatWentRight:["Protocol-owned liquidity was genuinely innovative","Created new tokenomics design space","Strong community and meme culture","Treasury grew to billions"],
whatWentWrong:["7,000% APY mathematically unsustainable","Rebasing created illusion of gains","Game theory assumed irrational cooperation","No real revenue to back emissions","Once confidence broke, reflexivity killed it"],
theAlpha:["Rebasing tokens are mathematical illusions","Game theory with real money leads to defection","Protocol-owned liquidity concept survives in Balancer/Velodrome","Sustainable APY is 3-15%, not 7,000%","Memes are not monetary policy"],
keyPeople:[{role:"Founder",name:"Zeus (pseudonymous)"},{role:"Protocol",name:"Olympus DAO"},{role:"Concept",name:"(3,3) Game Theory"}],
lessons:["7,000% APY is mathematically impossible","Game theory with real money leads to defection","Protocol-owned liquidity was the real innovation","Rebasing tokens are easily manipulated","Cult followings don't prevent bank runs"],
phoenix:{enabled:false}},

{id:14,name:"Africrypt",category:"Ponzi",launchDate:"2019-01",deathDate:"2021-04",amount:3600000000,description:"Teen brothers vanished with 69,000 BTC.",fullDescription:"Ameer and Raees Cajee, ages 18 and 21, ran Africrypt from South Africa. When they accumulated 69,000 BTC ($3.6B), they claimed a hack, told investors NOT to report to police, and vanished.",causeOfDeath:"The 'hack' was a lie. Brothers transferred funds and disappeared. They allegedly told family they were going to try to 'recover' the funds. Neither seen since.",tags:["exit-scam","brothers"],type:"rug",
valueProposition:"Africrypt promised AI-driven trading with guaranteed returns. Young founders seemed like tech prodigies. South African investors had few local crypto options.",
whatWentRight:["Effective marketing to local market","Built trust through community presence","Young founders seemed innovative"],
whatWentWrong:["No verifiable trading strategy","Telling investors not to contact police","Classic Ponzi returns (too consistent)","No regulatory oversight","Trusted youth over verification"],
theAlpha:["If they say don't contact police, CONTACT POLICE","Age doesn't indicate trustworthiness","Guaranteed returns = guaranteed scam","Geographic scarcity creates vulnerability","Always verify trading claims independently"],
keyPeople:[{role:"Founder",name:"Ameer Cajee (18)"},{role:"Founder",name:"Raees Cajee (21)"},{role:"Status",name:"Fugitives"}],
lessons:["If they say don't contact police, contact police immediately","Young founders aren't automatically trustworthy","AI trading claims are usually fake","Consistent returns are a red flag","Verify independently or don't invest"],
phoenix:{enabled:false}},

{id:15,name:"BitConnect",category:"Ponzi",launchDate:"2016-01",deathDate:"2018-01",amount:3500000000,description:"OG crypto Ponzi. 1% daily returns. Carlos Matos became a meme.",fullDescription:"BitConnect promised 1% daily returns (3,780% APY) through a 'trading bot.' It used MLM recruitment and mandatory lockups. Carlos Matos's 'BITCONNEEECT!' scream at their conference became legendary cringe.",causeOfDeath:"Texas and North Carolina issued cease-and-desist orders. BCC crashed from $400+ to under $1 overnight. The 'trading bot' never existed.",tags:["ponzi","mlm","meme"],type:"rug",
valueProposition:"BitConnect promised passive income through lending. 1% daily seemed incredible but not impossible to naive investors. MLM structure incentivized recruitment over skepticism.",
whatWentRight:["Effective MLM recruitment machine","Memorable marketing (unfortunately)","Exploited crypto bull market FOMO","Built genuine community (of victims)"],
whatWentWrong:["1% daily is mathematically impossible","No actual trading bot existed","MLM structure was classic pyramid","Regulatory scrutiny inevitable","Exit was sudden and complete"],
theAlpha:["1% daily = 3,780% APY = impossible","MLM + crypto is always a scam","Mandatory lockups prevent bank runs until exit","Regulators eventually catch up","Meme conferences are warning signs"],
keyPeople:[{role:"Promoter",name:"Carlos Matos"},{role:"Founder",name:"Satish Kumbhani"},{role:"Promoter",name:"Glenn Arcaro"},{role:"Status",name:"DOJ indictments"}],
lessons:["1% daily (3,780% APY) is mathematically impossible","MLM recruitment = pyramid scheme","Trading bot claims are usually lies","Lockup periods hide insolvency","The louder the promotion, the bigger the scam"],
phoenix:{enabled:false}},

{id:16,name:"Genesis Trading",category:"Lending",launchDate:"2013-01",deathDate:"2023-01",amount:3000000000,description:"DCG's lending arm had $2.36B exposure to 3AC.",fullDescription:"Genesis was Digital Currency Group's institutional lending desk, handling billions in crypto loans. They lent $2.36B to Three Arrows Capital with inadequate collateral, trusting reputation over risk management.",causeOfDeath:"3AC collapse left a $2.36B hole. Genesis froze withdrawals, affecting Gemini Earn customers. Parent company DCG's bailout attempts failed. Bankruptcy followed.",tags:["contagion","gemini"],type:"collapse",
valueProposition:"Genesis was THE institutional crypto prime broker. DCG backing suggested stability. Gemini partnership added retail distribution through Earn program.",
whatWentRight:["Built dominant institutional lending position","Strong DCG backing and relationships","Gemini partnership expanded reach","Handled billions in volume"],
whatWentWrong:["$2.36B exposure to single counterparty","Trusted 3AC reputation over collateral","Risk management was relationship-based","Contagion spread to retail via Gemini Earn","DCG conflicts of interest unclear"],
theAlpha:["Institutional doesn't mean safe","Concentrated counterparty risk kills","Reputation-based lending is gambling","Yield programs inherit counterparty risk","Parent company backing has limits"],
keyPeople:[{role:"CEO",name:"Michael Moro"},{role:"Parent",name:"DCG/Barry Silbert"},{role:"Partner",name:"Gemini/Winklevoss"},{role:"Debtor",name:"3AC"}],
lessons:["Yield programs inherit counterparty risk","Even institutional players blow up","Concentrated exposure is always dangerous","DCG/Genesis/Grayscale conflicts were hidden","Relationship lending isn't risk management"],
phoenix:{enabled:false}},

{id:17,name:"StepN",category:"GameFi",launchDate:"2021-12",deathDate:"2022-06",amount:3000000000,description:"Move-to-earn required $1,000 sneaker NFTs to walk.",fullDescription:"StepN gamified walking - buy expensive sneaker NFTs, earn GST tokens while exercising. At peak, sneakers cost $1,000+. The app had millions of users walking for crypto.",causeOfDeath:"China banned the app. Ponzi dynamics required endless new players. When growth slowed, token crashed 95%+. 3 million users left with worthless NFTs.",tags:["move-to-earn","ponzinomics"],type:"collapse",
valueProposition:"StepN combined fitness motivation with earning potential. Walking is free, so earning while doing it seemed like pure upside. Social features added accountability.",
whatWentRight:["Genuinely motivated people to exercise","Viral growth through social features","Novel move-to-earn concept","Strong community engagement","Good mobile app UX"],
whatWentWrong:["$1,000+ NFT barrier to entry","Earnings required constant new players","China ban killed largest market","No sustainable tokenomics","Free walking shouldn't require $1,000 investment"],
theAlpha:["Barrier to entry kills mass adoption","Move-to-earn needs zero upfront cost","Geographic concentration is risk","Fitness apps work - crypto earnings don't scale","Ponzi dynamics always collapse"],
keyPeople:[{role:"Founder",name:"Yawn Rong"},{role:"Founder",name:"Jerry Huang"},{role:"Investor",name:"Sequoia Capital"},{role:"Investor",name:"Binance Labs"}],
lessons:["$1,000 NFTs to walk is absurd","Free alternatives always win eventually","Geographic bans can kill overnight","Move-to-earn needs sustainable model","Ponzi dynamics end the same way"],
phoenix:{enabled:false}},

{id:18,name:"PlusToken",category:"Ponzi",launchDate:"2018-05",deathDate:"2019-06",amount:2900000000,description:"Chinese MLM Ponzi with 3 million victims.",fullDescription:"PlusToken promised 10-30% monthly returns through 'arbitrage' and 'AI trading.' Operating primarily in China and Korea, it recruited through MLM. 3 million people invested before the exit.",causeOfDeath:"Chinese authorities arrested 109 members in 2020. Founders had already fled with billions. Stolen funds liquidation crashed Bitcoin markets multiple times.",tags:["ponzi","china"],type:"rug",
valueProposition:"PlusToken promised consistent monthly returns from arbitrage. Wallet app seemed legitimate. MLM incentives turned victims into recruiters.",
whatWentRight:["Slick wallet app seemed professional","MLM created viral growth","Tapped underserved Asian markets","Consistent payouts (while Ponzi grew)"],
whatWentWrong:["No actual arbitrage strategy","Pure MLM/pyramid structure","Returns paid from new deposits","Founders planned exit from start","Scale attracted regulatory attention"],
theAlpha:["Arbitrage bot claims are almost always fake","10-30% monthly is obviously impossible","MLM + crypto = guaranteed scam","Asian market vulnerability to Ponzis","Stolen fund liquidations crash markets"],
keyPeople:[{role:"Organizer",name:"Chen Bo"},{role:"Status",name:"109 arrested"},{role:"Victims",name:"3 million people"}],
lessons:["Arbitrage bot claims are always fake","10-30% monthly returns are impossible","MLM recruitment is pyramid scheme","Chinese authorities do prosecute","Ponzi liquidations crash markets"],
phoenix:{enabled:false}},

{id:19,name:"BAYC",category:"NFT",launchDate:"2021-04",deathDate:"2024-01",amount:2800000000,description:"From 150 ETH floor to under 10. Celebrities bought the top.",fullDescription:"Bored Ape Yacht Club was THE NFT status symbol. Celebrities from Bieber to Fallon paid millions. Floor hit 150 ETH ($400K+). Yuga Labs raised $450M at $4B valuation.",causeOfDeath:"NFT winter hit hard. Floor crashed 93%+ from peak. Celebrity holders down millions. Yuga's metaverse 'Otherside' underwhelmed. The hype cycle ended.",tags:["nft-winter","celebrities"],type:"collapse",
valueProposition:"BAYC offered status, community, and IP rights. Owning an Ape meant access to exclusive events, airdrops, and the 'club.' Celebrities provided aspirational marketing.",
whatWentRight:["Created genuine community and culture","IP rights were innovative for NFTs","Celebrity adoption drove awareness","Yuga built real company around it","Airdrops rewarded holders"],
whatWentWrong:["Prices disconnected from any fundamentals","Celebrity purchases marked the exact top","Metaverse pivot overpromised","No sustainable utility model","Speculation replaced community"],
theAlpha:["Celebrity purchases signal tops, not bottoms","NFT floors can crash 90%+ and not recover","IP rights don't ensure value","Community can't sustain speculative prices","Status symbols need constant new money"],
keyPeople:[{role:"Co-founder",name:"Wylie Aronow (Gordon Goner)"},{role:"Co-founder",name:"Greg Solano (Gargamel)"},{role:"Celebrity Buyer",name:"Justin Bieber"},{role:"Celebrity Buyer",name:"Jimmy Fallon"}],
lessons:["Celebrity purchases mark the top","NFT winter can destroy 90%+ of value","Status symbols require constant new buyers","Community can't sustain speculative prices","Floor price is meaningless in illiquid markets"],
phoenix:{enabled:false}},

{id:20,name:"Thodex",category:"Exchange",launchDate:"2017-01",deathDate:"2021-04",amount:2000000000,description:"Turkish CEO fled with $2B. Sentenced to 11,196 years.",fullDescription:"Thodex was Turkey's largest crypto exchange. CEO Faruk Fatih Özer announced 'partnership negotiations' requiring a temporary halt, then fled to Albania with approximately $2B in customer funds.",causeOfDeath:"400,000 users stranded. Özer caught after 2 years on the run. Turkish court sentenced him to 11,196 years in prison - one of the longest sentences ever for financial crime.",tags:["exit-scam","turkey"],type:"rug",
valueProposition:"Thodex was the dominant Turkish exchange, offering local currency trading and competitive fees. First-mover advantage in a large, underserved market.",
whatWentRight:["Built dominant local market position","Easy fiat on-ramp for Turkish users","Large user base (400K+)","Competitive trading fees"],
whatWentWrong:["Single point of failure (CEO controlled everything)","No regulatory oversight","Users had no recourse","Exit scam was clearly planned","'Maintenance' announcements are red flag"],
theAlpha:["Watch for sudden 'maintenance' announcements","Local exchanges have jurisdiction risk","Single founders controlling everything = risk","Turkey had no crypto regulation then","If CEO travels unexpectedly, withdraw immediately"],
keyPeople:[{role:"Founder/CEO",name:"Faruk Fatih Özer"},{role:"Status",name:"11,196 years prison"},{role:"Victims",name:"400,000 users"}],
lessons:["Watch for sudden maintenance announcements","Local exchanges carry jurisdiction risk","Verify where your exchange is regulated","If CEO announces travel, be suspicious","11,196 years shows Turkey takes fraud seriously"],
phoenix:{enabled:false}},

{id:21,name:"Solidly",category:"DeFi",launchDate:"2022-02",deathDate:"2022-03",amount:2000000000,description:"Andre Cronje quit crypto. $2B TVL vanished overnight.",fullDescription:"Solidly was Andre Cronje's ve(3,3) experiment combining Curve's vote-escrowed model with Olympus mechanics. It attracted $2B TVL in weeks based purely on Andre's reputation.",causeOfDeath:"Andre announced he was leaving crypto. Panic ensued. TVL fled overnight. The project proved that single-founder dependency is an existential risk.",tags:["abandoned","andre-cronje"],type:"collapse",
valueProposition:"Solidly promised to revolutionize DEX incentive alignment. Ve(3,3) would reward long-term stakers while creating sustainable liquidity. Andre's track record (Yearn, Keep3r) seemed to guarantee success.",
whatWentRight:["Ve(3,3) model was genuinely innovative","Attracted $2B TVL rapidly","Strong initial community interest","Model later succeeded as Velodrome"],
whatWentWrong:["100% dependent on single founder","Andre's departure was sudden","No succession plan or team","Speculation outpaced development","Community couldn't maintain it"],
theAlpha:["Single founder dependency is existential risk","Ve(3,3) model works when properly maintained (see Velodrome)","Reputation-driven TVL flees fast","Projects need teams, not individuals","Forking can save good ideas from bad execution"],
keyPeople:[{role:"Creator",name:"Andre Cronje"},{role:"Fork",name:"Velodrome (succeeded)"},{role:"Chain",name:"Fantom"}],
lessons:["Protocols dependent on one person are fragile","Ve(3,3) model works when properly run (see Velodrome)","Reputation-driven TVL can flee instantly","Always check team depth, not just founder","Good ideas can be forked and improved"],
phoenix:{enabled:false}},

{id:22,name:"IRON/TITAN",category:"DeFi",launchDate:"2021-05",deathDate:"2021-06",amount:1900000000,description:"Mark Cuban got rugged. TITAN went to zero.",fullDescription:"IRON Finance was a partially-collateralized algorithmic stablecoin on Polygon. Mark Cuban publicly invested and promoted it. TITAN was the governance token backing IRON.",causeOfDeath:"Classic death spiral: IRON lost peg, TITAN minted to defend, selling pressure crashed TITAN to $0.000000035. Mark Cuban lost money and called for regulation.",tags:["death-spiral","celebrity-victim"],type:"collapse",
valueProposition:"IRON promised a capital-efficient stablecoin - partially algorithmic to reduce collateral requirements. High yields attracted liquidity miners.",
whatWentRight:["Attracted significant TVL quickly","Celebrity endorsement drove awareness","Polygon deployment meant low fees","Yield farming was lucrative briefly"],
whatWentWrong:["Partial collateralization is unstable","Death spiral mechanism well-known","Celebrity endorsement isn't due diligence","Algorithmic stability failed under pressure","No circuit breakers"],
theAlpha:["Even billionaires get rugged","Partial collateral = full risk","Death spirals are predictable and preventable","Celebrity investors don't do due diligence","Algo stables need 150%+ collateral minimum"],
keyPeople:[{role:"Celebrity Investor",name:"Mark Cuban"},{role:"Protocol",name:"IRON Finance"},{role:"Chain",name:"Polygon"}],
lessons:["Even billionaires get rugged","Partially-collateralized stables are unstable","Celebrity endorsements mean nothing","Algorithmic stability requires overcollateralization","Death spirals are predictable"],
phoenix:{enabled:false}},

{id:23,name:"Finiko",category:"Ponzi",launchDate:"2019-01",deathDate:"2021-07",amount:1500000000,description:"Russian Ponzi promised 30% monthly. Inevitable collapse.",fullDescription:"Finiko operated in Russia and CIS countries promising 30% monthly returns through 'automated trading.' At peak, it processed $1.5B. Founder Kirill Doronin was a flashy Instagram influencer.",causeOfDeath:"Russian authorities arrested Doronin and associates. Pyramid collapsed. Thousands of Russians lost savings. Doronin sentenced to prison.",tags:["ponzi","russia"],type:"rug",
valueProposition:"Finiko promised passive income through automated trading. Flashy marketing and influencer founder attracted young Russian investors.",
whatWentRight:["Effective social media marketing","Influencer founder drove recruitment","Tapped underserved Russian market","Slick branding and presentation"],
whatWentWrong:["30% monthly is obviously impossible","No actual trading strategy","Pure pyramid scheme","Regulatory crackdown inevitable","Founder's lifestyle was funded by investors"],
theAlpha:["30% monthly = 2,230% APY = impossible","Influencer founders are red flags","Russian market vulnerable to Ponzis","Flashy lifestyle funded by victims","CIS region has many similar scams"],
keyPeople:[{role:"Founder",name:"Kirill Doronin"},{role:"Status",name:"Arrested"},{role:"Country",name:"Russia"}],
lessons:["30% monthly is mathematically impossible","Influencer lifestyles funded by your money","Russian Ponzis are common","Automated trading claims are lies","If returns seem impossible, they are"],
phoenix:{enabled:false}},

{id:24,name:"Wonderland TIME",category:"DeFi",launchDate:"2021-09",deathDate:"2022-01",amount:1200000000,description:"$1B treasury managed by convicted fraudster.",fullDescription:"Wonderland was an Olympus DAO fork with massive treasury. Pseudonymous treasury manager '0xSifu' controlled over $1B. ZachXBT discovered 0xSifu was Michael Patryn, co-founder of collapsed exchange QuadrigaCX.",causeOfDeath:"When 0xSifu's identity was revealed, confidence collapsed. The convicted fraudster had been managing a billion dollars. TIME crashed 80%+ as holders fled.",tags:["criminal","ohm-fork"],type:"collapse",
valueProposition:"Wonderland offered Olympus-style yields with active treasury management. 0xSifu was seen as a genius trader growing the treasury.",
whatWentRight:["Built massive treasury ($1B+)","Strong community initially","Treasury was actively managed","Fork of proven Olympus model"],
whatWentWrong:["Treasury manager was convicted fraudster","Pseudonymity hid criminal history","No background checks on key roles","Founder Daniele defended 0xSifu initially","Trust destroyed instantly upon reveal"],
theAlpha:["Anonymous treasury managers = unknown risk","Background checks are essential for key roles","Pseudonymity can hide criminal history","$1B controlled by unknown person is insane","ZachXBT provides valuable accountability"],
keyPeople:[{role:"Treasury",name:"0xSifu (Michael Patryn)"},{role:"Founder",name:"Daniele Sestagalli"},{role:"Investigator",name:"ZachXBT"},{role:"Connection",name:"QuadrigaCX"}],
lessons:["Anonymous treasury managers are unacceptable risk","Background checks matter for DeFi roles","Pseudonymity can hide criminal history","On-chain sleuths provide accountability","Past fraud predicts future fraud"],
phoenix:{enabled:false}},

{id:25,name:"Ronin Bridge",category:"Bridge",launchDate:"2021-06",deathDate:"2022-03",amount:625000000,description:"North Korea stole $625M. Hack unnoticed for 6 days.",fullDescription:"Ronin was Axie Infinity's Ethereum sidechain bridge. North Korea's Lazarus Group compromised validator keys through a fake job offer. They drained $625M - the hack went unnoticed for 6 days.",causeOfDeath:"A user trying to withdraw discovered the bridge was empty. Investigation revealed state-sponsored hackers had compromised 5 of 9 validator keys. Largest DeFi hack ever at the time.",tags:["hack","north-korea"],type:"hack",
valueProposition:"Ronin enabled fast, cheap transactions for Axie Infinity by bridging to Ethereum. Essential infrastructure for the game's economy.",
whatWentRight:["Enabled Axie's massive scale","Fast and cheap transactions","Bridge worked smoothly until hack"],
whatWentWrong:["Only 9 validators (too few)","5 keys compromised = game over","Hack undetected for 6 days","Social engineering via fake job offer","No monitoring for large withdrawals"],
theAlpha:["Nation-state hackers target crypto bridges","Social engineering bypasses technical security","Bridges are high-value targets","Validator key security is critical","Monitor for unusual large transactions"],
keyPeople:[{role:"Hacker",name:"Lazarus Group (North Korea)"},{role:"Victim",name:"Sky Mavis/Axie"},{role:"Method",name:"Fake job offer phishing"}],
lessons:["Nation-state hackers target bridges","Social engineering is a major attack vector","Bridges need more validators/security","Monitor for unusual transactions","6 days unnoticed = inadequate monitoring"],
phoenix:{enabled:false}},

{id:26,name:"Mango Markets",category:"DeFi",launchDate:"2021-08",deathDate:"2022-10",amount:114000000,description:"Avraham Eisenberg bragged about exploit. Got arrested.",fullDescription:"Mango Markets was a Solana perps DEX. Avraham Eisenberg manipulated the MNGO oracle price 10x using $10M, then borrowed $114M against his inflated position. He publicly bragged it was 'legal trading.'",causeOfDeath:"Eisenberg's public bragging led to DOJ arrest. He argued it was legitimate arbitrage. Jury disagreed. Convicted of commodities fraud and manipulation.",tags:["manipulation","arrested"],type:"hack",
valueProposition:"Mango offered decentralized perpetuals trading on Solana with cross-collateralization and high leverage. Innovative product for DeFi traders.",
whatWentRight:["Innovative perps product on Solana","Cross-collateralization was useful","Active trading community","Good UX for DeFi perps"],
whatWentWrong:["Oracle could be manipulated","Insufficient liquidity depth","No circuit breakers on price moves","Eisenberg's 'exploit' was predictable","Bragging publicly led to arrest"],
theAlpha:["Oracle manipulation is existential risk for perps","Public bragging attracts prosecutors","'Legitimate trading strategy' defense doesn't work","DeFi exploits can be prosecuted","Solana DeFi had growing pains"],
keyPeople:[{role:"Exploiter",name:"Avraham Eisenberg"},{role:"Protocol",name:"Mango Markets"},{role:"Status",name:"Convicted"}],
lessons:["Bragging about exploits attracts prosecution","Oracle manipulation is existential DeFi risk","'Legal trading' defense doesn't always work","DeFi exploiters can face criminal charges","Perps need robust oracle solutions"],
phoenix:{enabled:false}},

{id:27,name:"Badger DAO",category:"DeFi",launchDate:"2020-12",deathDate:"2021-12",amount:120000000,description:"Frontend hack. Users unknowingly approved wallet drains.",fullDescription:"Badger DAO brought Bitcoin to DeFi. Hackers compromised Badger's Cloudflare API key and injected malicious scripts into the frontend. Users visiting the site unknowingly approved transactions draining their wallets.",causeOfDeath:"$120M drained while users thought they were using the normal app. The frontend looked identical - only the approval requests were malicious. Highlighted that frontends are attack vectors.",tags:["hack","frontend"],type:"hack",
valueProposition:"Badger enabled Bitcoin holders to earn yield in DeFi without selling BTC. Vaults automated yield strategies. BTC-focused DeFi was underserved.",
whatWentRight:["Filled real gap for BTC in DeFi","Strong technical team","Vault strategies were sound","Community-focused governance"],
whatWentWrong:["Frontend security was inadequate","Cloudflare API key compromised","Users couldn't distinguish malicious approvals","$120M drained before detection","CDN dependency was single point of failure"],
theAlpha:["Frontends are attack vectors, not just smart contracts","Always verify what you're signing","Compromised CDN = compromised app","Hardware wallets show transaction details","Unlimited approvals are dangerous"],
keyPeople:[{role:"Protocol",name:"Badger DAO"},{role:"Attack Vector",name:"Cloudflare API"},{role:"Method",name:"Frontend injection"}],
lessons:["Frontends are attack vectors","Always check what you're signing","Compromised CDN = compromised app","Hardware wallets help but aren't foolproof","Unlimited token approvals are risky"],
phoenix:{enabled:false}}
];

const hallOfShame = [
{rank:1,id:'do-kwon',name:"Do Kwon",project:"Terra/LUNA",year:"2022",status:"Extradited to US",
extracted:"Unknown",peakMC:"$40B",victimLosses:"$40B+",
photoUrl:"images/do_kwon.jpg",viralQuote:"I don't debate the poor.",
description:"Built Terra ecosystem while mocking critics. When UST collapsed, his arrogant tweets became evidence of hubris. Arrested in Montenegro with fake passports, now facing US charges.",
viralMoment:"Arrogant tweets aged catastrophically as LUNA crashed from $119 to $0.00001.",
story:"Built Terra while mocking critics. When UST collapsed, tweets became evidence of hubris. Arrested with fake passports.",
tags:["terra","arrogance"],viralityScore:10,youtubeId:"KYlNI8U9TCw",videoType:"youtube"},

{rank:2,id:'sbf',name:"Sam Bankman-Fried",project:"FTX",year:"2022",status:"25 years prison",
extracted:"$8B+",peakMC:"$32B",victimLosses:"$8B+",
photoUrl:"images/sam_bankman_fried.jpg",viralQuote:"I didn't knowingly commingle funds.",
description:"Built $32B empire while stealing customer deposits. Played League of Legends during investor calls. Effective altruism was a cover. 25 years in federal prison.",
viralMoment:"Played League during investor calls while stealing $8B.",
story:"Built $32B empire while stealing deposits. Gave interviews playing games post-collapse. 25 years.",
tags:["ftx","fraud"],viralityScore:10,youtubeId:"20BEJouWBgY",videoType:"youtube"},

{rank:3,id:'su-zhu',name:"Su Zhu & Kyle Davies",project:"Three Arrows Capital",year:"2022",status:"Su Zhu arrested",
extracted:"$18B collapse",peakMC:"$18B AUM",victimLosses:"$3.5B+",
photoUrl:"images/_3_Su_Zhu___Kyle_Davies.jpg",viralQuote:"We are communicating with relevant parties.",
description:"Borrowed billions without collateral. When LUNA collapsed, they ghosted creditors and fled on a yacht. Su Zhu later arrested. Incredibly, launched new exchange for bankruptcy claims.",
viralMoment:"Lost $18B, ghosted creditors, fled on yacht, launched exchange for bankruptcy claims.",
story:"Borrowed without collateral. LUNA destroyed them. Fled on yacht. Su Zhu arrested.",
tags:["3ac","yacht"],viralityScore:9,youtubeId:"7SaHu3UVNCk",videoType:"youtube"},

{rank:4,id:'mashinsky',name:"Alex Mashinsky",project:"Celsius",year:"2022",status:"Arrested",
extracted:"$10M+",peakMC:"$12B deposits",victimLosses:"$4.7B",
photoUrl:"images/_4_Alex_Mashinsky.jpg",viralQuote:"Banks are not your friends!",
description:"Performed weekly AMAs attacking traditional banks while secretly gambling customer funds. Withdrew $10M personally before freezing customer withdrawals. Arrested for fraud.",
viralMoment:"Weekly AMAs attacking banks while withdrawing $10M before freeze.",
story:"Working-class hero act while gambling funds. Withdrew $10M before freeze. Arrested.",
tags:["celsius","hypocrisy"],viralityScore:9,youtubeId:"dv6_57Bowhs",videoType:"youtube"},

{rank:5,id:'richard-heart',name:"Richard Heart",project:"HEX/PulseChain",year:"2023",status:"SEC charged, fugitive",
extracted:"$12B+ sacrifices",peakMC:"$12B",victimLosses:"Unknown",
photoUrl:"images/_5_Richard_Heart.png",viralQuote:"Delayed gratification is key.",
description:"Built cult following who 'sacrificed' billions to him. Flaunts $100M watch collection while followers lose money. SEC charged him. Fled to Europe. Still posting flexes.",
viralMoment:"$100M in watches while telling followers to 'sacrifice' to him.",
story:"Cult following. Billions in 'sacrifices'. SEC charged. Fled to Europe.",
tags:["hex","cult"],viralityScore:8,youtubeId:"NPVOxgqKZsI",videoType:"youtube"},

{rank:6,id:'ruja',name:"Dr. Ruja Ignatova",project:"OneCoin",year:"2017",status:"FBI Top 10 Wanted",
extracted:"$4B+",peakMC:"N/A",victimLosses:"$4B+",
photoUrl:"images/_6_Dr__Ruja_Ignatova.jpg",viralQuote:"Nobody will talk about Bitcoin!",
description:"The 'Crypto Queen' sold $4B of fake cryptocurrency. OneCoin had no blockchain - it was pure MLM fraud. Vanished in 2017. FBI Most Wanted with $250K reward. Possibly dead.",
viralMoment:"Stadium events for fake crypto. No blockchain. Vanished 2017.",
story:"'Crypto Queen' sold fake crypto. No blockchain existed. $250K FBI reward.",
tags:["onecoin","fbi"],viralityScore:10,youtubeId:"ZoklPHEjXl4",videoType:"youtube"},

{rank:7,id:'africrypt',name:"Cajee Brothers",project:"Africrypt",year:"2021",status:"Fugitives",
extracted:"69,000 BTC",peakMC:"N/A",victimLosses:"$3.6B",
photoUrl:"images/_7_Cajee_Brothers.jpg",viralQuote:"Don't report to authorities.",
description:"Ages 18 and 21, they accumulated 69,000 BTC then claimed a 'hack' while telling investors NOT to contact police. Vanished completely. Still at large with billions.",
viralMoment:"Ages 18 and 21, vanished with 69K BTC after telling investors NOT to call police.",
story:"Teen brothers claimed hack, told investors not to report, vanished with billions.",
tags:["exit-scam","brothers"],viralityScore:9,youtubeId:"HqmS-2D7SVM",videoType:"youtube"},

{rank:8,id:'thodex',name:"Faruk Fatih Özer",project:"Thodex",year:"2021",status:"11,196 years prison",
extracted:"$2B",peakMC:"N/A",victimLosses:"$2B",
photoUrl:"images/_8_Faruk_Fatih_Ozer.jpg",viralQuote:"Just partnership negotiations.",
description:"CEO of Turkey's largest exchange announced 'partnership negotiations' then fled with $2B. Caught after 2 years. Sentenced to 11,196 years - Turkey doesn't play around.",
viralMoment:"Announced 'partnership negotiations', fled to Albania with $2B. 11,196 year sentence.",
story:"Turkey's largest exchange. Fake partnership claim. 400K victims. Record sentence.",
tags:["exit-scam","turkey"],viralityScore:9,youtubeId:"JWApzXk745Q",videoType:"youtube"},

{rank:9,id:'carlos',name:"Carlos Matos",project:"BitConnect",year:"2018",status:"Meme legend",
extracted:"Promoter",peakMC:"$3.5B",victimLosses:"$3.5B",
photoUrl:"images/_9_Carlos_Matos.jpg",viralQuote:"BITCONNEEEEECT!",
description:"His unhinged conference scream became crypto's most famous meme. Promoted obvious Ponzi to thousands. Now does paid cameos. The face of crypto cringe forever.",
viralMoment:"'BITCONNEEECT!' scream at conference became legendary crypto cringe.",
story:"Conference scream became legendary. Promoted Ponzi. Now does cameos.",
tags:["bitconnect","meme"],viralityScore:10,youtubeId:"lCcwn6bGUtU",videoType:"youtube"},

{rank:10,id:'karpeles',name:"Mark Karpelès",project:"Mt. Gox",year:"2014",status:"Suspended sentence",
extracted:"850,000 BTC lost",peakMC:"N/A",victimLosses:"$8.5B+",
photoUrl:"images/_10_Mark_Karpeles.jpg",viralQuote:"Technical difficulties.",
description:"CEO when Mt. Gox lost 850,000 BTC. Either massive incompetence or fraud - jury's still out. Creditors waited 10+ years for partial recovery. The original crypto catastrophe.",
viralMoment:"'Technical difficulties' while 850,000 BTC vanished over years.",
story:"Lost 850K BTC. Incompetence or fraud unclear. Original crypto catastrophe.",
tags:["mtgox","og"],viralityScore:8,youtubeId:"lV6ikdGTzLk",videoType:"youtube"}
];

const pumpFunHorrors = [
{id:'baby',name:"The Baby Incident",perpetrator:"Mikael Owns",date:"2024",wtfFactor:10,emoji:"👶🔥",
extracted:"~$30K",peakMC:"Unknown",
shortDescription:"Tied up baby on stream. Got Pump.fun livestreams banned forever.",
fullStory:"Appeared with restrained infant during launch. Massive outrage. Pump.fun disabled all streams.",
aftermath:"Streams disabled permanently. Mikael vanished.",
tags:["banned"],videoId:"ZRWkTFqkhgY",videoType:"youtube"},

{id:'fire',name:"Fire Guy",perpetrator:"Anonymous",date:"2024",wtfFactor:9,emoji:"🔥😱",
extracted:"~$50K",peakMC:"~$500K",
shortDescription:"Set himself on fire for token pump. Hospitalized.",
fullStory:"Doused self in flammable liquid during launch stream. Severe burns. Token pumped briefly.",
aftermath:"Clip viral. Condition unknown.",
tags:["fire"],videoId:"",videoType:"twitter-search"},

{id:'cereal',name:"Cereal Guy",perpetrator:"Anonymous",date:"2024",wtfFactor:7,emoji:"🥣🤮",
extracted:"~$20K",peakMC:"~$200K",
shortDescription:"Ate cereal from toilet on stream. We've fallen far.",
fullStory:"Promised to eat cereal from toilet if token hit market cap. It did. He delivered.",
aftermath:"Became meme. Token zero.",
tags:["cereal"],videoId:"",videoType:"twitter-search"},

{id:'school',name:"School Livestream",perpetrator:"Anonymous Teen",date:"2024",wtfFactor:8,emoji:"🏫📱",
extracted:"~$15K",peakMC:"~$300K",
shortDescription:"Launched token during class. Teacher found out.",
fullStory:"Teen ran pump.fun stream during school. Teacher eventually noticed. Video went viral.",
aftermath:"Unknown if caught.",
tags:["school"],videoId:"",videoType:"twitter-search"},

{id:'grandma',name:"Grandma Launch",perpetrator:"Anonymous",date:"2024",wtfFactor:6,emoji:"👵💰",
extracted:"~$40K",peakMC:"~$800K",
shortDescription:"Put confused grandmother on stream without her understanding.",
fullStory:"Filmed confused elderly relative to pump token. She had no idea what was happening.",
aftermath:"Grandma still confused.",
tags:["grandma"],videoId:"",videoType:"twitter-search"},

{id:'mikael-owns',name:"Mikael Owns",perpetrator:"Mikael Owns",date:"2024",wtfFactor:10,emoji:"🎭💀",
extracted:"$200K+",peakMC:"Various",
shortDescription:"Serial pump.fun deployer. Multiple incidents including baby.",
fullStory:"Notorious figure responsible for multiple shocking streams including the baby incident.",
aftermath:"Still active. Platform's poster child.",
tags:["stunts"],videoId:"gKHJYuG4yFQ",videoType:"youtube"}
];

const trenchLegends = [
{id:'quant',name:"The Quant Kid",perpetrator:"15-year-old",project:"Various",date:"2024",wtfFactor:8,emoji:"👦📈",
extracted:"$50K+",peakMC:"Various",victimLosses:"Unknown",
blockchain:"Solana",contractAddress:"various",
shortDescription:"15-year-old made $50K+ sniping memecoins. Posted gains on TikTok.",
fullStory:"Teenager documented memecoin trading on TikTok. Made $50K+ in weeks through sniping and quick flips. Became symbol of 'degen' culture.",
aftermath:"Still trading. Has following.",
tags:["teen"],photoUrl:"images/quant.jpg",videoId:"jZUeyFKw7u4",videoType:"youtube"},

{id:'hawk',name:"Hawk Tuah Token",perpetrator:"Community",project:"$HAWK",date:"2024",wtfFactor:9,emoji:"🦅💦",
extracted:"$5M+",peakMC:"$500M",victimLosses:"Millions",
blockchain:"Solana",contractAddress:"HAWKThXRcNL9ZGZKqgUXLm4W8tnRZ7U6MVdEepSutj34",
shortDescription:"Viral meme girl launched token. 97% crash. Insiders dumped.",
fullStory:"Hailey Welch (Hawk Tuah girl) launched $HAWK token. Hit $500M market cap. Crashed 97% as insiders dumped. Now facing lawsuits.",
aftermath:"Class action lawsuit filed.",
tags:["celebrity"],photoUrl:"images/Hawk_Tuah_Token.jpg",videoId:"qwQTX2vbgRk",videoType:"youtube"},

{id:'squid',name:"Squid Game Token",perpetrator:"Anonymous",project:"$SQUID",date:"2021",wtfFactor:10,emoji:"🦑🎮",
extracted:"$12M",peakMC:"$2.8B",victimLosses:"$12M+",
blockchain:"BSC",contractAddress:"0x87230146E138d3F296a9a77e497A2A83012e9Bc5",
shortDescription:"Pumped 310,000% in a week. Rug pulled in 5 minutes.",
fullStory:"Rode Netflix show hype. Anti-sell mechanism trapped buyers. Pumped to $2,861, rugged to $0.0007 in 5 minutes. Devs got away.",
aftermath:"Never caught. Perfect rug.",
tags:["honeypot"],photoUrl:"images/Squid_Game_Token.jpg",videoId:"CpR2kMxy7O8",videoType:"youtube"},

{id:'anubis',name:"AnubisDAO",perpetrator:"Unknown",project:"AnubisDAO",date:"2021",wtfFactor:9,emoji:"🐕‍🦺💀",
extracted:"$60M",peakMC:"$60M",victimLosses:"$60M",
blockchain:"Ethereum",contractAddress:"0x38a0df9a08d18dc06cd91fc7ec94a0acdf28d994",
shortDescription:"$60M raised in 20 hours. Drained same day. Fastest major rug.",
fullStory:"OHM fork. $60M in 20 hours. All ETH transferred out same day. 'Phishing' excuse.",
aftermath:"ZachXBT traced funds. Fastest large rug ever.",
tags:["speedrun"],videoId:"97bHgDkf3pE",videoType:"youtube"},

{id:'faze',name:"FaZe Save The Kids",perpetrator:"FaZe Kay",project:"$KIDS",date:"2021",wtfFactor:8,emoji:"🎮🤑",
extracted:"~$30K",peakMC:"~$2-3M",victimLosses:"Hundreds of thousands",
blockchain:"BSC",contractAddress:"0x7acf49997e9598843cb9051389fa755969e551bb",
shortDescription:"Gaming influencers scammed teen fans with 'charity' token.",
fullStory:"50M+ followers. Anti-whale code secretly changed. Kay dumped. Coffeezilla exposed.",
aftermath:"Kay fired. Paid $400-500K refunds.",
tags:["influencer"],photoUrl:"images/FaZe_Save_The_Kids.png",videoId:"6fxtayFVwxQ",videoType:"youtube"},

{id:'ice',name:"Ice Poseidon",perpetrator:"Paul Denino",project:"CxCoin",date:"2022",wtfFactor:10,emoji:"🎥💩",
extracted:"$500K",peakMC:"Unknown",victimLosses:"$500K",blockchain:"Ethereum",
shortDescription:"Admitted on camera: 'I just didn't care.' Zero consequences.",
fullStory:"Raised $500K. Coffeezilla confronted. Openly admitted didn't care about investors.",
aftermath:"No legal consequences. Still streams.",
tags:["confession"],photoUrl:"images/ice_pos.jpg",videoId:"3NA8Ee3RF5E",videoType:"youtube"},

{id:'evil-ape',name:"Evil Ape",perpetrator:"Evil Ape",project:"Evolved Apes",date:"2021",wtfFactor:7,emoji:"🦍😈",
extracted:"$2.7M",peakMC:"$2.7M",victimLosses:"$2.7M",blockchain:"Ethereum",
shortDescription:"Named himself 'Evil Ape'. People trusted him. He rugged.",
fullStory:"NFT project. Dev literally called Evil Ape. Drained 798 ETH. Game never made.",
aftermath:"Community tried 'Fight Back Apes'. Never caught.",
tags:["nft"],photoUrl:"images/Evil_Ape.jpg",videoId:"jLBvfEdxjYU",videoType:"youtube"}
];

const typeLabels = {rug:"RUG PULL",hack:"HACKED",collapse:"COLLAPSED"};
const typeColors = {rug:"#ff2d55",hack:"#ff9500",collapse:"#bf5af2"};
